##############################################################################
#MediaTek Inc. (C) 2018. All rights reserved.
#Copyright Statement:
#This software/firmware and related documentation ("MediaTek Software") are
#protected under relevant copyright laws. The information contained herein is
#confidential and proprietary to MediaTek Inc. and/or its licensors. Without
#the prior written permission of MediaTek inc. and/or its licensors, any
#reproduction, modification, use or disclosure of MediaTek Software, and
#information contained herein, in whole or in part, shall be strictly
#prohibited.
#BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
#THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
#RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
#ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
#WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
#WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
#NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
#RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
#INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
#TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
#RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
#OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
#SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
#RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
#STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
#ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
#RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
#MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
#CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#The following software/firmware and/or related documentation ("MediaTek
#Software") have been modified by MediaTek Inc. All revisions are subject to
#any receiver's applicable license agreements with MediaTek Inc.
##############################################################################

ccflags-y += -I$(srctree)/drivers/soc/mediatek/mtk-memory

ifneq ($(MIDEMO_BUILD), true)
ccflags-y += -Wall -Werror
cppflags-y += -Wall -Werror
endif

snd-amp-rt9114-objs := mtk_alsa_amp_rt9114.o mtk_ini_parser.o
snd-amp-rt9120-objs := mtk_alsa_amp_rt9120.o mtk_ini_parser.o
snd-amp-rt9119-objs := mtk_alsa_amp_rt9119.o mtk_ini_parser.o
snd-amp-tas5805-objs := mtk_amp_tas5805.o mtk_ini_parser.o
snd-amp-ntp8928-objs := mtk_amp_ntp8928.o mtk_ini_parser.o
snd-amp-ad82089-objs := mtk_amp_ad82089.o mtk_ini_parser.o

obj-$(CONFIG_SND_SOC_MEDIATEK_DTV) += snd-amp-rt9114.o
obj-$(CONFIG_SND_SOC_MEDIATEK_DTV) += snd-amp-rt9120.o
obj-$(CONFIG_SND_SOC_MEDIATEK_DTV) += snd-amp-rt9119.o
obj-$(CONFIG_SND_SOC_MEDIATEK_DTV) += snd-amp-tas5805.o
obj-$(CONFIG_SND_SOC_MEDIATEK_DTV) += snd-amp-ntp8928.o
obj-$(CONFIG_SND_SOC_MEDIATEK_DTV) += snd-amp-ad82089.o

KBUILD_EXTRA_SYMBOLS += $(MDRV_MTKDRV_METAUTIL_SRC_DIR)/Module.symvers
