/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/*
 * Copyright (c) 2022 MediaTek Inc.
 */
#ifndef	__LINUX_SND_OFFLOAD_MEDIATEK_H
#define	__LINUX_SND_OFFLOAD_MEDIATEK_H

/*----------------------------------------------------*/
/* define*/
/*----------------------------------------------------*/
/* version */
#define	SND_OFFLOAD_MTK_UAPI_VER	0x0001

/* kcontrol */
#define K_CAPTURE_CTRL "Capture controls"
#define	K_UTPA_CTRL "Utopia controls"
#define	K_DUPLEX_CTRL "Duplex mm controls"

struct audio_offload_hwdep_reg;
struct audio_offload_hwdep_string_cmd;
#define SNDRV_HWDEP_IOCTL_REG_READ_BYTE _IOWR('H', 0x10, struct audio_offload_hwdep_reg)
#define SNDRV_HWDEP_IOCTL_REG_READ_WORD _IOWR('H', 0x11, struct audio_offload_hwdep_reg)
#define SNDRV_HWDEP_IOCTL_REG_WRITE_BYTE _IOW('H', 0x12, struct audio_offload_hwdep_reg)
#define SNDRV_HWDEP_IOCTL_REG_WRITE_WORD _IOW('H', 0x13, struct audio_offload_hwdep_reg)
#define SNDRV_HWDEP_IOCTL_STR_COMMAND _IOW('H', 0x14, struct audio_offload_hwdep_string_cmd)

/* card name */
#define	M_LAPAF_TVSOC		"mtktvsndcard"

/* audio */
#define AUDIO_STRING_NAME_MAX_LENGTH	64
#define	 AUDIO_OFFLOAD_COOK_MAX_NUM_CODECS	5

/* pcm */
#define AUDIO_COMMON_PCM_IO_NAME_LENGTH 32
/*----------------------------------------------------*/
/* enum*/
/*----------------------------------------------------*/
typedef unsigned long long AUDIO_OFFLOAD_VIRT;

typedef enum {
	AUDIO_OFFLOAD_DSP_DEC,                            //0
	AUDIO_OFFLOAD_DSP_SE,                             //1//1
	AUDIO_OFFLOAD_DSP_ADV,                            //2//2
	AUDIO_OFFLOAD_DSP_MAD                             //3//3
} AUDIO_OFFLOAD_DSP_TYPE;

typedef enum {
	AUDIO_OFFLOAD_PCM_CMD_ALL, /* GET */
	AUDIO_OFFLOAD_PCM_CMD_NONBLOCKING, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_MULTICH, /* GET */
	AUDIO_OFFLOAD_PCM_CMD_MIXING, /* GET */
	AUDIO_OFFLOAD_PCM_CMD_MIXINGGROUP, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_BUFFER, /* GET only */
	AUDIO_OFFLOAD_PCM_CMD_BUFFERDURATION, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_READPTR, /* GET only */
	AUDIO_OFFLOAD_PCM_CMD_WRITEPTR, /* GET only */
	AUDIO_OFFLOAD_PCM_CMD_CHANNEL, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_SAMPLERATE, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_BITWIDTH, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_BIGENDIAN, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_TIMESTAMP, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_WEIGHTING, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_VOLUME, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_BUFFERLEVEL, /* GET only */
	AUDIO_OFFLOAD_PCM_CMD_MUTE, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_BUFFERSIZE, /* GET only */
	AUDIO_OFFLOAD_PCM_CMD_DATAPORT, /* SET */
	AUDIO_OFFLOAD_PCM_CMD_AUTORUN, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_VOLUME_DB, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_EASING_TYPE, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_EASING_DURATION, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_EASING_GAIN, /* SET/GET */
	AUDIO_OFFLOAD_PCM_CMD_FREERUN, /* SET */
	AUDIO_OFFLOAD_PCM_CMD_OUTPUT_SAMPLECNT, /* GET (AUDIO_PCM_TIME_PAIR)*/
	AUDIO_OFFLOAD_PCM_CMD_EMPTY_SAMPLECNT, /* GET */
	AUDIO_OFFLOAD_PCM_CMD_IRQ_INTERVAL, /* SET */
} AUDIO_OFFLOAD_PCM_COMMAND;

enum {
	AUDIO_OFFLOAD_TYPE_MIN,
	AUDIO_OFFLOAD_WritePreInitTable,
	AUDIO_OFFLOAD_SetDspBaseAddr,
	AUDIO_OFFLOAD_Initialize,
	AUDIO_OFFLOAD_GetDspMadBaseAddr,
	AUDIO_OFFLOAD_SetPowerOn,
	AUDIO_OFFLOAD_Monitor,
	AUDIO_OFFLOAD_SetOutputInfo,
	AUDIO_OFFLOAD_SetPathInfo,
	AUDIO_OFFLOAD_GetPathInfo,
	AUDIO_OFFLOAD_InputSwitch,
	AUDIO_OFFLOAD_SetSourceInfo,
	AUDIO_OFFLOAD_SetMixModeMute,
	AUDIO_OFFLOAD_SetMixModeVolume,
	AUDIO_OFFLOAD_SetAbsoluteVolume,
	AUDIO_OFFLOAD_SetMute,
	AUDIO_OFFLOAD_SPDIF_SetMute,
	AUDIO_OFFLOAD_OpenDecodeSystem,
	AUDIO_OFFLOAD_GetDecodeSystem,
	AUDIO_OFFLOAD_SetDecodeSystem,
	AUDIO_OFFLOAD_ReleaseDecodeSystem,
	AUDIO_OFFLOAD_SetMpegInfo,
	AUDIO_OFFLOAD_GetMpegInfo,
	AUDIO_OFFLOAD_SetAC3PInfo,
	AUDIO_OFFLOAD_GetAC3PInfo,
	AUDIO_OFFLOAD_SetASFParm,
	AUDIO_OFFLOAD_SetDecodeCmd,
	AUDIO_OFFLOAD_GetMAD_LOCK,
	AUDIO_OFFLOAD_SetCommAudioInfo,
	AUDIO_OFFLOAD_GetCommAudioInfo,
	AUDIO_OFFLOAD_SetAudioParam2,
	AUDIO_OFFLOAD_GetAudioInfo2,
	AUDIO_OFFLOAD_SYSTEM_Control,
	AUDIO_OFFLOAD_SIF_SendCmd,
	AUDIO_OFFLOAD_SIF_SetBandSetup,
	AUDIO_OFFLOAD_SIF_IsPALType,
	AUDIO_OFFLOAD_SIF_SetPALType,
	AUDIO_OFFLOAD_SIF_SetSoundMode,
	AUDIO_OFFLOAD_TriggerSifPLL,
	AUDIO_OFFLOAD_SIF_GetAudioStatus,
	AUDIO_OFFLOAD_SIF_GetSoundMode,
	AUDIO_OFFLOAD_SIF_StartAutoStandardDetection,
	AUDIO_OFFLOAD_SIF_GetResultOfAutoStandardDetection,
	AUDIO_OFFLOAD_SIF_SetThreshold,
	AUDIO_OFFLOAD_SIF_SetPrescale,
	AUDIO_OFFLOAD_SIF_SetStandard,
	AUDIO_OFFLOAD_SPDIF_Monitor,
	AUDIO_OFFLOAD_SPDIF_SetMode,
	AUDIO_OFFLOAD_SPDIF_GetMode,
	AUDIO_OFFLOAD_SPDIF_SetSCMS,
	AUDIO_OFFLOAD_SPDIF_HWEN,
	AUDIO_OFFLOAD_SPDIF_ChannelStatus_CTRL,
	AUDIO_OFFLOAD_DigitalOut_SetDeviceCapability,
	AUDIO_OFFLOAD_HDMI_GetNonpcmFlag,
	AUDIO_OFFLOAD_HDMI_RX_SetNonpcm,
	AUDIO_OFFLOAD_HDMI_RX_GetNonPCM,
	AUDIO_OFFLOAD_PCM_Open,
	AUDIO_OFFLOAD_PCM_Close,
	AUDIO_OFFLOAD_PCM_Start,
	AUDIO_OFFLOAD_PCM_Stop,
	AUDIO_OFFLOAD_PCM_Set,
	AUDIO_OFFLOAD_PCM_Get,
	AUDIO_OFFLOAD_PCM_Read,
	AUDIO_OFFLOAD_PCM_Write,
	AUDIO_OFFLOAD_PCM_Flush,
	AUDIO_OFFLOAD_SND_ProcessEnable,
	AUDIO_OFFLOAD_SND_SetParam1,
	AUDIO_OFFLOAD_SND_GetParam1,
	AUDIO_OFFLOAD_SOUND_GetParam,
	AUDIO_OFFLOAD_SoundEffect_SetParam,
	AUDIO_OFFLOAD_ADVSOUND_ProcessEnable,
	AUDIO_OFFLOAD_ADVSOUND_SubProcessEnable,
	AUDIO_OFFLOAD_ADVSND_SetParam,
	AUDIO_OFFLOAD_COPY_Parameter,
	AUDIO_OFFLOAD_MM2_initAesInfo,
	AUDIO_OFFLOAD_MM2_checkAesInfo,
	AUDIO_OFFLOAD_MM2_inputAesFinished,
	AUDIO_OFFLOAD_GetAdcPort,
	AUDIO_OFFLOAD_DecodeEs_Write,
	AUDIO_OFFLOAD_SetCommand,
	AUDIO_OFFLOAD_DecodedPcm_Read,
	AUDIO_OFFLOAD_GetFirstTimeStamp,
	AUDIO_OFFLOAD_SetDecoderId,
	AUDIO_OFFLOAD_SyncMode,
	AUDIO_OFFLOAD_WriteRegByte,
	AUDIO_OFFLOAD_ReadRegByte,
	AUDIO_OFFLOAD_SetSystemInfo,
	AUDIO_OFFLOAD_PushTlvTable,
	AUDIO_OFFLOAD_TYPE_MAX,

	AUDIO_DUPLEX_TYPE_MIN,
	AUDIO_DUPLEX_SetDecoderId,
	AUDIO_DUPLEX_TYPE_MAX,

	AUDIO_CAPTURE_TYPE_MIN,
	AUDIO_CAPTURE_PCM_SetCmdDataPort,
	AUDIO_CAPTURE_PCM_GetDeviceId,
	AUDIO_CAPTURE_TYPE_MAX,
};

typedef enum {
	AUDIO_OFFLOAD_SPDIF_INPUT				  = 3,
	AUDIO_OFFLOAD_I2S_INPUT					  = 4,
	AUDIO_OFFLOAD_HDMI_INPUT				  = 5,
	AUDIO_OFFLOAD_SRC_INPUT					  = 7,

	AUDIO_OFFLOAD_DSP1_DVB_INPUT			  = 0x00,
	AUDIO_OFFLOAD_DSP1_DVB1_INPUT			  = 0x10,
	AUDIO_OFFLOAD_DSP1_SPDIF_INPUT			  = 0x20,
	AUDIO_OFFLOAD_DSP1_SPDIFx1_INPUT		  = 0x30,
	AUDIO_OFFLOAD_DSP1_HDMI_INPUT			  = 0x40,
	AUDIO_OFFLOAD_DSP1_HDMIx1_INPUT			  = 0x50,
	AUDIO_OFFLOAD_DSP1_CardRD_INPUT			  = 0x60,
	AUDIO_OFFLOAD_DSP1_SIF_INPUT			  = 0x70,
	AUDIO_OFFLOAD_DSP1_MM_INPUT				  = 0x80,

	AUDIO_OFFLOAD_DSP2_DVB_INPUT			  = 0x01,
	AUDIO_OFFLOAD_DSP2_DVB1_INPUT			  = 0x11,
	AUDIO_OFFLOAD_DSP2_SPDIF_INPUT			  = 0x21,
	AUDIO_OFFLOAD_DSP2_SPDIFx1_INPUT		  = 0x31,
	AUDIO_OFFLOAD_DSP2_HDMI_INPUT			  = 0x41,
	AUDIO_OFFLOAD_DSP2_HDMIx1_INPUT			  = 0x51,
	AUDIO_OFFLOAD_DSP2_CardRD_INPUT			  = 0x61,
	AUDIO_OFFLOAD_DSP2_SIF_INPUT			  = 0x71,

	AUDIO_OFFLOAD_DSP3_DVB_INPUT			  = 0x06,
	AUDIO_OFFLOAD_DSP3_DVB1_INPUT			  = 0x16,
	AUDIO_OFFLOAD_DSP3_SPDIF_INPUT			  = 0x26,
	AUDIO_OFFLOAD_DSP3_SPDIFx1_INPUT		  = 0x36,
	AUDIO_OFFLOAD_DSP3_HDMI_INPUT			  = 0x46,
	AUDIO_OFFLOAD_DSP3_HDMIx1_INPUT			  = 0x56,
	AUDIO_OFFLOAD_DSP3_CardRD_INPUT			  = 0x66,
	AUDIO_OFFLOAD_DSP3_SIF_INPUT			  = 0x76,

	AUDIO_OFFLOAD_DSP4_DVB_INPUT			  = 0x08,
	AUDIO_OFFLOAD_DSP4_DMARD_INPUT			  = 0x58,
	AUDIO_OFFLOAD_DSP4_SIF_INPUT			  = 0x78,

	AUDIO_OFFLOAD_AUIN0_INPUT				  = 0x02,
	AUDIO_OFFLOAD_AUIN1_INPUT				  = 0x12,
	AUDIO_OFFLOAD_AUIN2_INPUT				  = 0x22,
	AUDIO_OFFLOAD_AUIN3_INPUT				  = 0x32,
	AUDIO_OFFLOAD_AUIN4_INPUT				  = 0xA2,
	AUDIO_OFFLOAD_AUIN5_INPUT				  = 0xB2,
	AUDIO_OFFLOAD_AUMIC_INPUT				  = 0x72,

	AUDIO_OFFLOAD_ADC2_AUIN0_INPUT			  = 0x09,
	AUDIO_OFFLOAD_ADC2_AUIN1_INPUT			  = 0x19,
	AUDIO_OFFLOAD_ADC2_AUIN2_INPUT			  = 0x29,
	AUDIO_OFFLOAD_ADC2_AUIN3_INPUT			  = 0x39,
	AUDIO_OFFLOAD_ADC2_AUIN4_INPUT			  = 0xA9,
	AUDIO_OFFLOAD_ADC2_AUIN5_INPUT			  = 0xB9,
	AUDIO_OFFLOAD_ADC2_AUMIC_INPUT			  = 0x79,

	AUDIO_OFFLOAD_DMA_READER_INPUT			  = 0x0E,

	AUDIO_OFFLOAD_NULL_INPUT				  = 0xFF,
} AUDIO_OFFLOAD_INPUT_TYPE;

typedef enum {
	AUDIO_OFFLOAD_GROUP_MAIN,
	AUDIO_OFFLOAD_GROUP_SCART,
	AUDIO_OFFLOAD_GROUP_SPDIF,
	AUDIO_OFFLOAD_GROUP_SUB,
	AUDIO_OFFLOAD_GROUP_MAIN2,
	AUDIO_OFFLOAD_GROUP_INVALID
} AUDIO_OFFLOAD_SWITCH_GROUP;

typedef enum {
	AUDIO_OFFLOAD_SOURCE_INFO_INVALID = -1,
	AUDIO_OFFLOAD_SOURCE_DTV_IN = 0,
	AUDIO_OFFLOAD_SOURCE_ATV_IN,
	AUDIO_OFFLOAD_SOURCE_HDMI_IN,
	AUDIO_OFFLOAD_SOURCE_ADC_IN,
	AUDIO_OFFLOAD_SOURCE_MM_IN,
	AUDIO_OFFLOAD_SOURCE_SPDIF_IN,
	AUDIO_OFFLOAD_SOURCE_KTV_IN,
	AUDIO_OFFLOAD_SOURCE_GAME_IN,
	AUDIO_OFFLOAD_SOURCE_KTV_STB_IN
} AUDIO_OFFLOAD_SOURCE_INFO_TYPE;

/*<Enum for Audio data capture source selection*/
typedef enum {
	AUDIO_OFFLOAD_CAPTURE_CH1,
	/*<DatafromDIG1inputport*/
	AUDIO_OFFLOAD_CAPTURE_CH2,
	/*<DatafromDIG2inputport*/
	AUDIO_OFFLOAD_CAPTURE_CH3,
	/*<DatafromDIG3inputport*/
	AUDIO_OFFLOAD_CAPTURE_CH4,
	/*<DatafromDIG4inputport*/
	AUDIO_OFFLOAD_CAPTURE_CH5,
	/*<DatafromDIG5inputport*/
	AUDIO_OFFLOAD_CAPTURE_CH6,
	/*<DatafromDIG6inputport*/
	AUDIO_OFFLOAD_CAPTURE_CH7,
	/*<DatafromDIG7inputport*/
	AUDIO_OFFLOAD_CAPTURE_CH8,
	/*<DatafromDIG8inputport*/
	AUDIO_OFFLOAD_CAPTURE_CH9,
	/*<DatafromDIG9inputport*/
	AUDIO_OFFLOAD_CAPTURE_PCM,
	/*<PurePCMout=DataCH5*/
	AUDIO_OFFLOAD_CAPTURE_PCM_DELAY,
	/*<PCM+Delayout*/
	AUDIO_OFFLOAD_CAPTURE_PCM_SE,
	/*<PCM+Delay+SEout*/
	AUDIO_OFFLOAD_CAPTURE_ADC,
	/*<DatafromADC1inputport*/
	AUDIO_OFFLOAD_CAPTURE_AUOUT0,
	/*<DataforDAC0outputport*/
	AUDIO_OFFLOAD_CAPTURE_AUOUT1,
	/*<DataforDAC1outputport*/
	AUDIO_OFFLOAD_CAPTURE_AUOUT2,
	/*<DataforDAC2outputport*/
	AUDIO_OFFLOAD_CAPTURE_AUOUT3,
	/*<DataforDAC3outputport*/
	AUDIO_OFFLOAD_CAPTURE_I2S_OUT,
	/*<DataforI2Soutputport*/
	AUDIO_OFFLOAD_CAPTURE_SPDIF_OUT,
	/*<DataforSPDIFoutputport*/
	AUDIO_OFFLOAD_CAPTURE_MIXER,
	/*<DataforaudiodataMixer*/
	AUDIO_OFFLOAD_CAPTURE_ADC2,
	/*<DatafromADC2inputport*/
	AUDIO_OFFLOAD_CAPTURE_ADC1_AUIN0_INPUT,
	/*ADC1-Line-in[0]*/
	AUDIO_OFFLOAD_CAPTURE_ADC1_AUIN1_INPUT,
	/*ADC1-Line-in[1]*/
	AUDIO_OFFLOAD_CAPTURE_ADC1_AUIN2_INPUT,
	/*ADC1-Line-in[2]*/
	AUDIO_OFFLOAD_CAPTURE_ADC1_AUIN3_INPUT,
	/*ADC1-Line-in[3]*/
	AUDIO_OFFLOAD_CAPTURE_ADC1_AUIN4_INPUT,
	/*ADC1-Line-in[4]*/
	AUDIO_OFFLOAD_CAPTURE_ADC1_AUIN5_INPUT,
	/*ADC1-Line-in[5]*/
	AUDIO_OFFLOAD_CAPTURE_ADC1_AUMIC_INPUT,
	/*ADC1-Micphone-in*/
	AUDIO_OFFLOAD_CAPTURE_ADC2_AUIN0_INPUT,
	/*ADC2-Line-in[0]*/
	AUDIO_OFFLOAD_CAPTURE_ADC2_AUIN1_INPUT,
	/*ADC2-Line-in[1]*/
	AUDIO_OFFLOAD_CAPTURE_ADC2_AUIN2_INPUT,
	/*ADC2-Line-in[2]*/
	AUDIO_OFFLOAD_CAPTURE_ADC2_AUIN3_INPUT,
	/*ADC2-Line-in[3]*/
	AUDIO_OFFLOAD_CAPTURE_ADC2_AUIN4_INPUT,
	/*ADC2-Line-in[4]*/
	AUDIO_OFFLOAD_CAPTURE_ADC2_AUIN5_INPUT,
	/*ADC2-Line-in[5]*/
	AUDIO_OFFLOAD_CAPTURE_ADC2_AUMIC_INPUT,
	/*ADC2-Micphone-in*/
	AUDIO_OFFLOAD_CAPTURE_SPEAKER,
	/*<Speakerout(Delay+SE+VolumeBalance)*/
	AUDIO_OFFLOAD_CAPTURE_PCM_DECIM,
	/*<PCM+Delay+Decimationout*/
	AUDIO_OFFLOAD_CAPTURE_I2S_RX0,
	/*<I2SRX0(SD0)*/
	AUDIO_OFFLOAD_CAPTURE_I2S_RX1,
	/*<I2SRX1(SD1)*/
	AUDIO_OFFLOAD_CAPTURE_I2S_RX0_RX1,
	/*<I2SRX0+RX1(SD0+SD1)-Customized*/
	AUDIO_OFFLOAD_CAPTURE_PCM_RENDER_6CH,
	/*PCMRender5.1channel*/
	AUDIO_OFFLOAD_CAPTURE_MCH_PCM_8CH,
	/*multichannelPCMinput8ch,L/R/C/LFE/LS/RS/...*/
	AUDIO_OFFLOAD_CAPTURE_HP_DMX,
	/*Headphoneout*/
	AUDIO_OFFLOAD_CAPTURE_MAX_NUM,
	/*<MAXcapturesourcenumber*/
	AUDIO_OFFLOAD_CAPTURE_NULL = 0xFF,
	/*<Nocaupuresource*/
} AUDIO_OFFLOAD_CAPTURE_SOURCE_TYPE;

typedef enum {
	AUDIO_OFFLOAD_PCM_VOL,
	AUDIO_OFFLOAD_MIC_VOL,
	AUDIO_OFFLOAD_MP3_VOL,
	AUDIO_OFFLOAD_GAME1_VOL,
	AUDIO_OFFLOAD_GAME2_VOL,
	AUDIO_OFFLOAD_ECHO1_VOL,
	AUDIO_OFFLOAD_ECHO2_VOL,
} AUDIO_OFFLOAD_MIX_VOL_TYPE;

typedef enum {
	AUDIO_OFFLOAD_DEC_INVALID					   = -1,
	AUDIO_OFFLOAD_DEC_ID1						   =  0,
	AUDIO_OFFLOAD_DEC_ID2						   =  1,
	AUDIO_OFFLOAD_DEC_ID3						   =  2,
	AUDIO_OFFLOAD_DEC_ID4						   =  3,
	AUDIO_OFFLOAD_DEC_ID5						   =  4,
	AUDIO_OFFLOAD_DEC_MAX						   =  5
} AUDIO_OFFLOAD_DEC_ID;

typedef enum {
	AUDIO_DUPLEX_DEC_INVALID					   = -1,
	AUDIO_DUPLEX_DEC_ID1						   =  0,
	AUDIO_DUPLEX_DEC_ID2						   =  1,
	AUDIO_DUPLEX_DEC_ID3						   =  2,
	AUDIO_DUPLEX_DEC_ID4						   =  3,
	AUDIO_DUPLEX_DEC_ID5						   =  4,
	AUDIO_DUPLEX_DEC_MAX						   =  5
} AUDIO_DUPLEX_DEC_ID;

typedef enum {
	AUDIO_OFFLOAD_CONNECT_MAIN,
	AUDIO_OFFLOAD_CONNECT_SUB,
	AUDIO_OFFLOAD_CONNECT_SCART,
	AUDIO_OFFLOAD_CONNECT_DATA_CAPTURE,
	AUDIO_OFFLOAD_CONNECT_KTV,
	AUDIO_OFFLOAD_CONNECT_NULL,
} AUDIO_OFFLOAD_OUTPORT_SOURCE_TYPE;

typedef enum {
	AUDIO_OFFLOAD_DSP_ID_DEC = 0x00,
	AUDIO_OFFLOAD_DSP_ID_SND,
	AUDIO_OFFLOAD_DSP_ID_R2,
	AUDIO_OFFLOAD_DSP_ID_ALL = 0xFF
} AUDIO_OFFLOAD_DSP_ID;

typedef enum {
	AUDIO_OFFLOAD_TSP_0,
	AUDIO_OFFLOAD_TSP_1,
	AUDIO_OFFLOAD_TSP_2,
	AUDIO_OFFLOAD_TSP_3,
	AUDIO_OFFLOAD_TSP_4,
	AUDIO_OFFLOAD_TSP_5,
	AUDIO_OFFLOAD_TSP_6,
	AUDIO_OFFLOAD_TSP_7,
	AUDIO_OFFLOAD_TSP_MAX,
} AUDIO_OFFLOAD_STC_SOURCE;

typedef enum {
	AUDIO_OFFLOAD_AUOUT0_OUTPUT,
	AUDIO_OFFLOAD_AUOUT1_OUTPUT,
	AUDIO_OFFLOAD_AUOUT2_OUTPUT,
	AUDIO_OFFLOAD_AUOUT3_OUTPUT,
	AUDIO_OFFLOAD_SPDIF_OUTPUT,
	AUDIO_OFFLOAD_I2S_OUTPUT,
	AUDIO_OFFLOAD_HP_OUTPUT,
	AUDIO_OFFLOAD_I2S2_OUTPUT,
	AUDIO_OFFLOAD_HDMI_ARC_OUTPUT,
	AUDIO_OFFLOAD_HDMI_OUTPUT,
	AUDIO_OFFLOAD_I2S3_OUTPUT,
	AUDIO_OFFLOAD_I2S4_OUTPUT,
	AUDIO_OFFLOAD_NULL_OUTPUT = 0xFF,
} AUDIO_OFFLOAD_OUTPUT_TYPE;

typedef enum {
	AUDIO_OFFLOAD_PATH_0,
	AUDIO_OFFLOAD_PATH_1,
	AUDIO_OFFLOAD_PATH_2,
	AUDIO_OFFLOAD_PATH_3,
	AUDIO_OFFLOAD_PATH_4,
	AUDIO_OFFLOAD_PATH_5,
	AUDIO_OFFLOAD_PATH_6,
	AUDIO_OFFLOAD_PATH_7,
	AUDIO_OFFLOAD_PATH_8,
	AUDIO_OFFLOAD_PATH_9,
	AUDIO_OFFLOAD_PATH_MAIN					 = 4,

	AUDIO_OFFLOAD_PATH_CH1					 = 0,
	AUDIO_OFFLOAD_PATH_CH2,
	AUDIO_OFFLOAD_PATH_CH3,
	AUDIO_OFFLOAD_PATH_CH4,
	AUDIO_OFFLOAD_PATH_CH5,
	AUDIO_OFFLOAD_PATH_CH6,
	AUDIO_OFFLOAD_PATH_CH7,
	AUDIO_OFFLOAD_PATH_CH8,
	AUDIO_OFFLOAD_PATH_CH9,
	AUDIO_OFFLOAD_PATH_CH10,

	AUDIO_OFFLOAD_T3_PATH_AUOUT0				= 0x30,
	AUDIO_OFFLOAD_T3_PATH_AUOUT1				= 0x31,
	AUDIO_OFFLOAD_T3_PATH_AUOUT2				= 0x32,
	AUDIO_OFFLOAD_T3_PATH_AUOUT3				= 0x33,
	AUDIO_OFFLOAD_T3_PATH_I2S				   = 0x34,
	AUDIO_OFFLOAD_T3_PATH_SPDIF				 = 0x35,
	AUDIO_OFFLOAD_T3_PATH_I2S2				  = 0x36,
	AUDIO_OFFLOAD_T3_PATH_HDMI				  = 0x37,
	AUDIO_OFFLOAD_T3_PATH_LR					= 0x38,
	AUDIO_OFFLOAD_T3_PATH_PCM_CAPTURE1		  = 0x39,
	AUDIO_OFFLOAD_T3_PATH_PCM_CAPTURE2		  = 0x3A,
	AUDIO_OFFLOAD_T3_PATH_DMA_WRITER1		   = 0x3B,
	AUDIO_OFFLOAD_T3_PATH_PCM_CAPTURE3		  = 0x3C,
	AUDIO_OFFLOAD_T3_PATH_ARC				   = 0x3D,
	AUDIO_OFFLOAD_T3_PATH_MIXER_MAIN			= 0x40,
	AUDIO_OFFLOAD_T3_PATH_MIXER_SECONDARY	   = 0x41,
	AUDIO_OFFLOAD_T3_PATH_MIXER_DMA_IN		  = 0x42,
	AUDIO_OFFLOAD_T3_PATH_MIXER_MCH_IN		  = 0x43,
	AUDIO_OFFLOAD_T3_PATH_PCM_CAPTURE4		  = 0x44,

	AUDIO_OFFLOAD_PATH_SW_DMA_0				 = 0x50,
	AUDIO_OFFLOAD_PATH_SW_DMA_1				 = 0x51,
	AUDIO_OFFLOAD_PATH_HW_DMA_0				 = 0x52,
	AUDIO_OFFLOAD_PATH_HW_DMA_1				 = 0x53,

	AUDIO_OFFLOAD_PATH_NULL					 = 0xFF
} AUDIO_OFFLOAD_PATH_TYPE;

typedef enum {
	AUDIO_OFFLOAD_DVB_INVALID			   = 0xFF,

	AUDIO_OFFLOAD_DVB_NONE				  = 0x00,
	AUDIO_OFFLOAD_DVB_MPEG,
	AUDIO_OFFLOAD_DVB_AC3,
	AUDIO_OFFLOAD_DVB_AC3P,
	AUDIO_OFFLOAD_DVB_AAC,
	AUDIO_OFFLOAD_DVB_MP3,
	AUDIO_OFFLOAD_DVB_WMA,
	AUDIO_OFFLOAD_DVB_CDLPCM,
	AUDIO_OFFLOAD_DVB_RA8LBR,
	AUDIO_OFFLOAD_DVB_XPCM,
	AUDIO_OFFLOAD_DVB_TONE,
	AUDIO_OFFLOAD_DVB_DTS,
	AUDIO_OFFLOAD_DVB_MS10_DDT,
	AUDIO_OFFLOAD_DVB_MS10_DDC,
	AUDIO_OFFLOAD_DVB_WMA_PRO,
	AUDIO_OFFLOAD_DVB_FLAC,
	AUDIO_OFFLOAD_DVB_VORBIS,
	AUDIO_OFFLOAD_DVB_DTSLBR,
	AUDIO_OFFLOAD_DVB_AMR_NB,
	AUDIO_OFFLOAD_DVB_AMR_WB,
	AUDIO_OFFLOAD_DVB_DRA,
	AUDIO_OFFLOAD_DVB_DolbyTrueHDBypass,
	AUDIO_OFFLOAD_DVB_DTSHDADO,
	AUDIO_OFFLOAD_DVB_DTSXLL,
	AUDIO_OFFLOAD_DVB_ES_Bypass,
	AUDIO_OFFLOAD_DVB_AC4,
	AUDIO_OFFLOAD_DVB_MPEG_H,
	AUDIO_OFFLOAD_DVB_OPUS,
	AUDIO_OFFLOAD_DVB_MAT,
	AUDIO_OFFLOAD_DVB_DTSX,
	AUDIO_OFFLOAD_DVB_HDMIRxPCM,
	AUDIO_OFFLOAD_DVB_MAX,

	AUDIO_OFFLOAD_DVB2_NONE				 = 0x30,
	AUDIO_OFFLOAD_DVB2_MPEG,
	AUDIO_OFFLOAD_DVB2_AC3,
	AUDIO_OFFLOAD_DVB2_MP3,
	AUDIO_OFFLOAD_DVB2_AAC,
	AUDIO_OFFLOAD_DVB2_GAAC,
	AUDIO_OFFLOAD_DVB2_AC3P,
	AUDIO_OFFLOAD_DVB2_DDE,
	AUDIO_OFFLOAD_DVB2_DTSE,
	AUDIO_OFFLOAD_DVB2_XPCM,
	AUDIO_OFFLOAD_DVB2_KTV,
	AUDIO_OFFLOAD_DVB2_KTV2,
	AUDIO_OFFLOAD_DVB2_DTS,
	AUDIO_OFFLOAD_DVB2_TONEGEN,
	AUDIO_OFFLOAD_DVB2_DolbyTrueHDBypass,
	AUDIO_OFFLOAD_DVB2_DTSHDADO,
	AUDIO_OFFLOAD_DVB2_AC4,
	AUDIO_OFFLOAD_DVB2_MPEG_H,
	AUDIO_OFFLOAD_DVB2_MAT,
	AUDIO_OFFLOAD_DVB2_DTSX,
	AUDIO_OFFLOAD_DVB2_HDMIRxPCM,
	AUDIO_OFFLOAD_DVB2_MAX,

	AUDIO_OFFLOAD_ATV_NONE				  = 0xB0,
	AUDIO_OFFLOAD_ATV_BTSC,
	AUDIO_OFFLOAD_ATV_EIAJ,
	AUDIO_OFFLOAD_ATV_PAL,
	AUDIO_OFFLOAD_ATV_FM_RADIO,
	AUDIO_OFFLOAD_ATV_MAX,

	AUDIO_OFFLOAD_ATVENC_NONE			   = 0xC0,
	AUDIO_OFFLOAD_ATVENC_FMTX,
	AUDIO_OFFLOAD_ATVENC_BTSC,
	AUDIO_OFFLOAD_ATVENC_MAX
} AUDIO_OFFLOAD_DEC_FORMAT;

typedef enum {
	AUDIO_OFFLOAD_AFIFO_0,
	AUDIO_OFFLOAD_AFIFO_1,
	AUDIO_OFFLOAD_AFIFO_2,
	AUDIO_OFFLOAD_AFIFO_3,
	AUDIO_OFFLOAD_AFIFO_4,
	AUDIO_OFFLOAD_AFIFO_5,
	AUDIO_OFFLOAD_AFIFO_MAX,
} AUDIO_OFFLOAD_AFIFO_SOURCE;

typedef enum {
	AUDIO_OFFLOAD_MM_OMX = 0x00,
	AUDIO_OFFLOAD_MM_VD,
	AUDIO_OFFLOAD_MM_INJECT,
	AUDIO_OFFLOAD_MM_FRAME_DECODE,
	AUDIO_OFFLOAD_MM_PASSTHROUGH,
	AUDIO_OFFLOAD_MM_MAX = 0xFF
} AUDIO_OFFLOAD_MM_TYPE;

typedef enum {
	AUDIO_OFFLOAD_FORCE_INVALID = -1,
	AUDIO_OFFLOAD_FORCE_ID1 = 0,
	AUDIO_OFFLOAD_FORCE_ID2 = 1,
	AUDIO_OFFLOAD_FORCE_ID3 = 2,
	AUDIO_OFFLOAD_FORCE_ID4 = 3,
	AUDIO_OFFLOAD_FORCE_ID5 = 4,
	AUDIO_OFFLOAD_FORCE_MAX = 5,
} AUDIO_OFFLOAD_FORCE_ADEC_ID;

typedef enum {
	Audio_OFFLOAD_DumpInfo_Off = 0x0,
	Audio_OFFLOAD_DumpInfo_Avsync = 0x1,
	Audio_OFFLOAD_DumpInfo_Dec1 = 0x2,
	Audio_OFFLOAD_DumpInfo_IoInfo = 0x4,
	Audio_OFFLOAD_DumpInfo_mmFileAVsync = 0x8,
	Audio_OFFLOAD_DumpInfo_All = 0x15,
	Audio_OFFLOAD_DumpInfo_AutoTest = 0x80,
} Audio_OFFLOAD_DumpInfo_Type;

typedef enum {
	AUDIO_OFFLOAD_MPEG_infoType_DecStatus,
	AUDIO_OFFLOAD_MPEG_infoType_SampleRate,
	AUDIO_OFFLOAD_MPEG_infoType_BitRate,
	AUDIO_OFFLOAD_MPEG_infoType_FrameNum,
	AUDIO_OFFLOAD_MPEG_infoType_SoundMode,
	AUDIO_OFFLOAD_MPEG_infoType_stereoMode,
	AUDIO_OFFLOAD_MPEG_infoType_Layer,
	AUDIO_OFFLOAD_MPEG_infoType_Header,
	AUDIO_OFFLOAD_MPEG_infoType_FFSpeed,
	AUDIO_OFFLOAD_MPEG_infoType_MMFileSize,
	AUDIO_OFFLOAD_MPEG_infoType_Emphasis,
	AUDIO_OFFLOAD_MPEG_DTV_AVSYNC_OFFSET,
	AUDIO_OFFLOAD_MPEG_infoType_PCMBufLev,
	AUDIO_OFFLOAD_MPEG_infoType_BufferDelay,
	AUDIO_OFFLOAD_MPEG_DTV_AVSYNC_DISABLE_SETTING,
	AUDIO_OFFLOAD_MPEG_MuteFrm_PcmHighLevel_Threshold_NumTimeOut,
	AUDIO_OFFLOAD_MPEG_MuteFrm_PcmHighLevel_MuteNum,
	AUDIO_OFFLOAD_MPEG_infoType_PcmHighLevel_Pcmdata
} AUDIO_OFFLOAD_MPEG_INFOTYPE;

typedef enum {
	AUDIO_OFFLOAD_AC3P_infoType_DecStatus,
	AUDIO_OFFLOAD_AC3P_infoType_SampleRate,
	AUDIO_OFFLOAD_AC3P_infoType_BitRate,
	AUDIO_OFFLOAD_AC3P_infoType_Dialnorm,
	AUDIO_OFFLOAD_AC3P_infoType_Acmod,
	AUDIO_OFFLOAD_AC3P_infoType_DrcMode,
	AUDIO_OFFLOAD_AC3P_infoType_DownmixMode,
	AUDIO_OFFLOAD_AC3P_infoType_MMFileSize,
	AUDIO_OFFLOAD_AC3P_infoType_syncSTC_in_mmTs,
	AUDIO_OFFLOAD_AC3P_infoType_hdmiTxBypass_enable,
	AUDIO_OFFLOAD_AC3P_infoType_AC3Type,
	AUDIO_OFFLOAD_AC3P_infoType_FrameSize,
	AUDIO_OFFLOAD_AC3P_infoType_BSMode,
	AUDIO_OFFLOAD_AC3P_infoType_BYTESWAP,
	AUDIO_OFFLOAD_AC3P_infoType_enableDolbyBulletin11,
	AUDIO_OFFLOAD_AC3P_DTV_AVSYNC_OFFSET,
	AUDIO_OFFLOAD_AC3P_infoType_hdmiAC3inSE,
	AUDIO_OFFLOAD_AC3P_DTV_AVSYNC_DISABLE_SETTING,
	AUDIO_OFFLOAD_AC3P_infoType_hdmi_in_support_DDP,
	AUDIO_OFFLOAD_AC3P_infoType_Drc_HighCutScale,
	AUDIO_OFFLOAD_AC3P_infoType_Drc_LowBootScale,
	AUDIO_OFFLOAD_AC3P_infoType_LoudnessMatching,
	AUDIO_OFFLOAD_AC3P_infoType_ATMOS_support,
	AUDIO_OFFLOAD_AC3P_infoType_Mixer_Balance,
	AUDIO_OFFLOAD_AC3P_infoType_DDP_AD_Substream,
	AUDIO_OFFLOAD_AC3P_infoType_AD_Mixer_Balance,
	AUDIO_OFFLOAD_AC3P_infoType_DDPEnc_Mode,
	AUDIO_OFFLOAD_AC3P_infoType_DDP_71_Stream,
	AUDIO_OFFLOAD_AC3P_infoType_SyncwordFound_Count,
	AUDIO_OFFLOAD_AC3P_infoType_Reset_Atmos_EVO_Index_Buffer,
} AUDIO_OFFLOAD_AC3P_INFOTYPE;

typedef enum {
	AUDIO_OFFLOAD_WMA_PARAMTYPE_VERSION,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_CHANNELS,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_SAMPLERATE,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_BYTERATE,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_BLOCKALIGN,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_ENCOPT,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_PARSINGBYAPP,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_BITS_PER_SAMPLE,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_CHANNELMASK,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_DRC_PARAM_EXIST,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_DRC_RMS_AMP_REF,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_DRC_RMS_AMP_TARGET,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_DRC_PEAK_AMP_REF,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_DRC_PEAK_AMP_TARGET,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_MAX_PACKET_SIZE,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_ADVANCEDENCODEOPT,
	AUDIO_OFFLOAD_WMA_PARAMTYPE_ADVANCEDENCODEOPT2,
} AUDIO_OFFLOAD_WMA_ASF_PARMTYPE;

typedef enum {
	AUDIO_OFFLOAD_DVB_DECCMD_STOP = 0x0,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAY,
	AUDIO_OFFLOAD_DVB_DECCMD_RESYNC,
	AUDIO_OFFLOAD_DVB_DECCMD_FREE_RUN,
	AUDIO_OFFLOAD_DVB_DECCMD_AVSYNC,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAYFILE,
	AUDIO_OFFLOAD_DVB_DECCMD_PAUSE,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAYFILETSP,
	AUDIO_OFFLOAD_DVB_DECCMD_STARTBROWSE,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAYFRAME,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAYFRAME_STAGE,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAYFRAME_GS,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAYMM_FILE2,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAY_AD,
	AUDIO_OFFLOAD_DVB_DECCMD_STOP_AD,
	AUDIO_OFFLOAD_DVB_DECCMD_SKIP,

	AUDIO_OFFLOAD_DVB2_DECCMD_STOP = 0x10,
	AUDIO_OFFLOAD_DVB2_DECCMD_PLAY,
	AUDIO_OFFLOAD_DVB2_DECCMD_RESYNC,
	AUDIO_OFFLOAD_DVB2_DECCMD_FREE_RUN,
	AUDIO_OFFLOAD_DVB2_DECCMD_AVSYNC,
	AUDIO_OFFLOAD_DVB2_DECCMD_PLAYFILE,
	AUDIO_OFFLOAD_DVB2_DECCMD_PAUSE,
	AUDIO_OFFLOAD_DVB2_DECCMD_PLAYFILETSP,

	AUDIO_OFFLOAD_DVB_DECCMD_TSP_FRAMEDECODE,
	AUDIO_OFFLOAD_DVB_DECCMD_PLAYFILETLV,
} AUDIO_OFFLOAD_DVB_DECCMDTYPE;

typedef enum {
	AUDIO_OFFLOAD_MMA_STOP,
	AUDIO_OFFLOAD_MMA_PLAY,
	AUDIO_OFFLOAD_MMA_PLAY_FILETSP,
	AUDIO_OFFLOAD_MMA_RESYNC,
	AUDIO_OFFLOAD_MMA_PLAY_FILE,
	AUDIO_OFFLOAD_MMA_BROWSE,
	AUDIO_OFFLOAD_MMA_PAUSE,
	AUDIO_OFFLOAD_MMA_PLAY_FRAME,
	AUDIO_OFFLOAD_MMA_PLAY_FRAME_GS,
	AUDIO_OFFLOAD_MMA_PLAY_AD,
	AUDIO_OFFLOAD_MMA_STOP_AD,
	AUDIO_OFFLOAD_MMA_AVSYNC,
	AUDIO_OFFLOAD_MMA_FREERUN,
	AUDIO_OFFLOAD_MMA_PLAY_FILETLV,
} AUDIO_OFFLOAD_MMA_AUDIO_CONTROL;

typedef enum {
	AUDIO_OFFLOAD_Comm_infoType_MMA_init = 0x60,
	AUDIO_OFFLOAD_Comm_infoType_MMA_finish,
	AUDIO_OFFLOAD_Comm_infoType_STC_Select,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_ChannelStatus_1st_64bits,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_ChannelStatus_2nd_64bits,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_ChannelStatus_3rd_64bits,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_UserData_1st_64bits,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_UserData_2nd_64bits,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_UserData_3rd_64bits,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_HWbypassmode,
	AUDIO_OFFLOAD_Comm_infoType_setHdmiDelay,
	AUDIO_OFFLOAD_Comm_infoType_Is_Audio_Sync,
	AUDIO_OFFLOAD_Comm_infoType_Get_Main_Input_Source_Info,
	AUDIO_OFFLOAD_Comm_infoType_Get_Sub_Input_Source_Info,
	AUDIO_OFFLOAD_Comm_infoType_Set_Input_Path,
	AUDIO_OFFLOAD_Comm_infoType_Get_Audio_Total_DDR_Size,

	AUDIO_OFFLOAD_Comm_infoType_ADEC1_capability = 0x70,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_setAudioDecoder,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_currAudDecStatus,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_AudioSyncStatus,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_sampleRate,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_bitRate,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_acmod,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_soundmod,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_reqDataSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_okFrmCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_errFrmCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_1ms_timeStamp,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_33bit_PTS,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_33bit_STCPTS_DIFF,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_esBuf_reqFlag,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_esBuf_reqAddr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_esBuf_reqSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_esBuf_informDataRdy,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_esBuf_currLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_pcmBuf_currLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_playControl,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_FF2X,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_mute,
	AUDIO_OFFLOAD_Comm_infoType_syncSTC_in_mmTs,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_play_wo_output,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_audio_unsupported,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_UNI_PCMOutCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_UNI_pcm_wptr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_UNI_pcm_decSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_UNI_PCMInput_Addr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_UNI_OutPCMLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_avSyncOffset,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Set_play_smpRate = 0x1000,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Get_PTS_latency,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Get_PCM_bufferEmpty,

	AUDIO_OFFLOAD_Comm_infoType_ADEC1_setDecParam = 0x8F,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecInfo1 = 0x90,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecInfo2,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecInfo3,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecInfo4,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecInfo5,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecInfo6,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecInfo7,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecInfo8,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getDecChannelInfo,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_getlatest_PTS,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_avsync_delay,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_avsync_delay_upperlimit,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_64bit_PTS,

	AUDIO_OFFLOAD_Comm_infoType_ADEC2_capability = 0xA0,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_setAudioDecoder,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_currAudDecStatus,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_AudioSyncStatus,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_sampleRate,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_bitRate,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_acmod,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_soundmod,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_reqDataSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_okFrmCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_errFrmCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_1ms_timeStamp,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_33bit_PTS,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_33bit_STCPTS_DIFF,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_esBuf_reqFlag,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_esBuf_reqAddr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_esBuf_reqSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_esBuf_informDataRdy,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_esBuf_currLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_pcmBuf_currLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_playControl,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_FF2X,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_mute,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_syncSTC_in_mmTs,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_play_wo_output,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_audio_unsupported,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_UNI_PCMOutCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_UNI_pcm_wptr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_UNI_pcm_decSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_UNI_PCMInput_Addr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_UNI_OutPCMLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_avSyncOffset,

	AUDIO_OFFLOAD_Comm_infoType_ADEC2_setDecParam = 0xBF,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecInfo1 = 0xC0,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecInfo2,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecInfo3,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecInfo4,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecInfo5,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecInfo6,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecInfo7,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecInfo8,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_getDecChannelInfo,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_64bit_PTS,

	AUDIO_OFFLOAD_Comm_infoType_ADEC3_capability = 0xD0,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_setAudioDecoder,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_currAudDecStatus,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_AudioSyncStatus,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_sampleRate,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_bitRate,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_acmod,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_soundmod,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_reqDataSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_okFrmCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_errFrmCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_1ms_timeStamp,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_33bit_PTS,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_33bit_STCPTS_DIFF,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_esBuf_reqFlag,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_esBuf_reqAddr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_esBuf_reqSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_esBuf_informDataRdy,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_esBuf_currLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_pcmBuf_currLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_playControl,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_FF2X,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_mute,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_syncSTC_in_mmTs,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_play_wo_output,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_audio_unsupported,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_UNI_PCMOutCnt,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_UNI_pcm_wptr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_UNI_pcm_decSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_UNI_PCMInput_Addr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_UNI_OutPCMLevel,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_avSyncOffset,

	AUDIO_OFFLOAD_Comm_infoType_ADEC3_setDecParam = 0xEF,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecInfo1 = 0xF0,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecInfo2,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecInfo3,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecInfo4,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecInfo5,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecInfo6,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecInfo7,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecInfo8,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getDecChannelInfo,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_getlatest_PTS,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_avsync_delay,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_avsync_delay_upperlimit,
	AUDIO_OFFLOAD_Comm_infoType_ADEC3_64bit_PTS,

	AUDIO_OFFLOAD_Comm_infoType_DecStatus = 0x00,
	AUDIO_OFFLOAD_Comm_infoType_SampleRate,
	AUDIO_OFFLOAD_Comm_infoType_SoundMode,
	AUDIO_OFFLOAD_Comm_infoType_DecOutMode,
	AUDIO_OFFLOAD_Comm_infoType_ChannelMode,
	AUDIO_OFFLOAD_Comm_infoType_MMFileSize,
	AUDIO_OFFLOAD_Comm_infoType_33Bit_PTS,
	AUDIO_OFFLOAD_Comm_infoType_33Bit_STCPTS_DIFF,
	AUDIO_OFFLOAD_Comm_infoType_1ms_PTS,
	AUDIO_OFFLOAD_Comm_infoType_DEC1_BufferSize,
	AUDIO_OFFLOAD_Comm_infoType_DEC1_BufferAddr,
	AUDIO_OFFLOAD_Comm_infoType_DEC1_MMTag,
	AUDIO_OFFLOAD_Comm_infoType_DEC1_MMResidualPCM,
	AUDIO_OFFLOAD_Comm_infoType_DEC1_ESBufferSize,
	AUDIO_OFFLOAD_Comm_infoType_DEC1_PCMBufferSize,
	AUDIO_OFFLOAD_Comm_infoType_DEC2_BufferSize,
	AUDIO_OFFLOAD_Comm_infoType_DEC2_BufferAddr = 0x10,
	AUDIO_OFFLOAD_Comm_infoType_DEC2_MMTag,
	AUDIO_OFFLOAD_Comm_infoType_DEC2_MMResidualPCM,
	AUDIO_OFFLOAD_Comm_infoType_DecodeErrorCnt,
	AUDIO_OFFLOAD_Comm_infoType_MM_FFx2,
	AUDIO_OFFLOAD_Comm_infoType_setBypassSPDIF_PAPB_chk,
	AUDIO_OFFLOAD_Comm_infoType_CompressBin_LoadCode,
	AUDIO_OFFLOAD_Comm_infoType_CompressBin_DDRAddress,
	AUDIO_OFFLOAD_Comm_infoType_DMAReader_BufferLevel,
	AUDIO_OFFLOAD_Comm_infoType_DMAReader_Command,
	AUDIO_OFFLOAD_Comm_infoType_SetSCMS,
	AUDIO_OFFLOAD_Comm_infoType_GetSCMS,
	AUDIO_OFFLOAD_Comm_infoType_ADC_InputGain,
	AUDIO_OFFLOAD_Comm_infoType_KTV_SetType,
	AUDIO_OFFLOAD_Comm_infoType_getSignal_Energy,
	AUDIO_OFFLOAD_Comm_infoType_getNR_Status,
	AUDIO_OFFLOAD_Comm_infoType_setNR_Threshold = 0x20,
	AUDIO_OFFLOAD_Comm_infoType_setSPDIF_FS,
	AUDIO_OFFLOAD_Comm_infoType_getSPDIF_FS,
	AUDIO_OFFLOAD_Comm_infoType_setSpdifDelay,
	AUDIO_OFFLOAD_Comm_infoType_ReadByte,
	AUDIO_OFFLOAD_Comm_infoType_WriteByte,
	AUDIO_OFFLOAD_Comm_infoType_hdmiTx_outType,
	AUDIO_OFFLOAD_Comm_infoType_hdmiTx_outFreq,
	AUDIO_OFFLOAD_Comm_infoType_PTS_info,
	AUDIO_OFFLOAD_Comm_infoType_RTSP_Mem,
	AUDIO_OFFLOAD_Comm_infoType_setSpdif_BufferProcess,
	AUDIO_OFFLOAD_Comm_infoType_DEC1_setBufferProcess,
	AUDIO_OFFLOAD_Comm_infoType_setES_REQ_SZ,
	AUDIO_OFFLOAD_Comm_infoType_AD_OutputStyle,
	AUDIO_OFFLOAD_Comm_infoType_getHDMI_CopyRight_C_Bit,
	AUDIO_OFFLOAD_Comm_infoType_getHDMI_CopyRight_L_Bit,
	AUDIO_OFFLOAD_Comm_infoType_Set_UNI_NEED_DECODE_FRMCNT = 0x30,
	AUDIO_OFFLOAD_Comm_infoType_Set_UNI_ES_Wptr,
	AUDIO_OFFLOAD_Comm_infoType_Get_UNI_ES_MEMCNT,
	AUDIO_OFFLOAD_Comm_infoType_Set_MENU_WT_PTR,
	AUDIO_OFFLOAD_Comm_infoType_Get_MENU_WT_PTR,
	AUDIO_OFFLOAD_Comm_infoType_Get_MENU_KEY_CNT,
	AUDIO_OFFLOAD_Comm_infoType_Get_CurSynthRate,
	AUDIO_OFFLOAD_Comm_infoType_ADC1_InputGain,
	AUDIO_OFFLOAD_Comm_infoType_mainpath_mute_status,
	AUDIO_OFFLOAD_Comm_infoType_spdif_mute_status,
	AUDIO_OFFLOAD_Comm_infoType_hdmiTX_mute_status,
	AUDIO_OFFLOAD_Comm_infoType_SRC_Compensation,
	AUDIO_OFFLOAD_Comm_infoType_Dump_Dsp_Info,
	AUDIO_OFFLOAD_Comm_infoType_Set_Video_STCPTS_DIFF,
	AUDIO_OFFLOAD_Comm_infoType_Get_UNI_ES_Base,
	AUDIO_OFFLOAD_Comm_infoType_Get_UNI_ES_Size,
	AUDIO_OFFLOAD_Comm_infoType_Get_UNI_PCM_Base = 0x40,
	AUDIO_OFFLOAD_Comm_infoType_Get_UNI_PCM_Size,
	AUDIO_OFFLOAD_Comm_infoType_Get_AccumEsCnt,
	AUDIO_OFFLOAD_Comm_infoType_DSP_PLL_Setting,
	AUDIO_OFFLOAD_Comm_infoType_Set_CallBackFunc,
	AUDIO_OFFLOAD_Comm_infoType_Set_ALSA_Mode,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_Unstable_Protect,
	AUDIO_OFFLOAD_Comm_infoType_HDMI_Unstable_Threshold,
	AUDIO_OFFLOAD_Comm_infoType_Set_TEE_Capibility,
	AUDIO_OFFLOAD_Comm_infoType_Parser_Spec,
	AUDIO_OFFLOAD_Comm_infoType_Get_MultiPlayer_Capability,
	AUDIO_OFFLOAD_Comm_infoType_Get_Parser_Architecture,
	AUDIO_OFFLOAD_Comm_infoType_Set_CfgCtrlRegs_Lock,
	AUDIO_OFFLOAD_Comm_infoType_DMAReader_BufferSize,
	AUDIO_OFFLOAD_Comm_infoType_PUSI_disable_Info,
	AUDIO_OFFLOAD_Comm_infoType_Set_Parser,
	AUDIO_OFFLOAD_Comm_infoType_Parser_Info = 0x50,
	AUDIO_OFFLOAD_Comm_infoType_Get_Dolby_TrueHD_Bypass_Capability,
	AUDIO_OFFLOAD_Comm_infoType_Set_DFS_PowerSave,
	AUDIO_OFFLOAD_Comm_infoType_Is_Decoder_In_R2,
	AUDIO_OFFLOAD_Comm_infoType_Get_audio_crash_status,
	AUDIO_OFFLOAD_Comm_infoType_mainAudio_setBufferProcess,
	AUDIO_OFFLOAD_Comm_infoType_Get_Main_Input_Type,
	AUDIO_OFFLOAD_Comm_infoType_Get_Sub_Input_Type,
	AUDIO_OFFLOAD_Comm_infoType_Multi_Channel,
	AUDIO_OFFLOAD_Comm_infoType_Vorbis_header_size = 0x5F,

	AUDIO_OFFLOAD_Comm_infoType_ES_PassThrough_DelaySmp = 0x2000,
	AUDIO_OFFLOAD_Comm_infoType_ES_PassThrough_PcmSmpRate,
	AUDIO_OFFLOAD_Comm_infoType_ES_PassThrough_HdmiSmpRate,

	AUDIO_OFFLOAD_Comm_infoType_HDMITx_Status,

	AUDIO_OFFLOAD_Comm_infoType_set_PAL_M_Type = 0x4000,
	AUDIO_OFFLOAD_Comm_infoType_set_PAL_N_Type,
	AUDIO_OFFLOAD_Comm_infoType_set_BTSC_M_Type,

	AUDIO_OFFLOAD_Comm_infoType_Get_SE_Input_Main_BufferBase = 0x8000,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_Input_Main_BufferSize,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_Output_Main_BufferBase,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_Output_Main_BufferSize,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_PROCESS_FRAME_SMP_UNIT,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_PROCESS_FETCH_CHANNELS,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_PROCESS_STORE_CHANNELS,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_PROCESS_FETCH_FRAME_BYTE_SIZE,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_PROCESS_STORE_FRAME_BYTE_SIZE,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_Input_Main_Buffer_Feed = 0x8100,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_Output_Main_Buffer_Consume,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_TEST_FIRST_FRAME_TAG_INFO = 0x8100,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_TEST_FRAME_TAG_INFO = 0x8101,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_Test_Init,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_Test_End,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_TONE_Test_Begin,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_PEQ_Test_Begin,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_GEQ_Test_Begin,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_AVC_Test_Begin,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_SRS_THEATER_SOUND_Begin,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_SONICEMOTION_ABS3D_Begin,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_BONGIOVI_DPS_Begin,
	AUDIO_OFFLOAD_Comm_infoType_Set_Debug_LOG_Level,
	AUDIO_OFFLOAD_Comm_infoType_Get_Dra_ChannelMode,
	AUDIO_OFFLOAD_Comm_infoType_Get_Max_DelayTime,
	AUDIO_OFFLOAD_Comm_infoType_Get_Min_DelayTime,
	AUDIO_OFFLOAD_Comm_infoType_Set_SE_DTS_STUDIOSOUND_3D_Begin,

	AUDIO_OFFLOAD_Comm_infoType_AUDIO_Get_ADEC0_R2CodeType,
	AUDIO_OFFLOAD_Comm_infoType_AUDIO_Get_ADEC1_R2CodeType,
	AUDIO_OFFLOAD_Comm_infoType_AUDIO_GetDsp2CodeType,
	AUDIO_OFFLOAD_Comm_infoType_LFE_Channel_Info,
	AUDIO_OFFLOAD_Comm_infoType_DAC_Clock_OnOff,
	AUDIO_OFFLOAD_Comm_infoType_MMTS_KEEP_33bit_PTS_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_AUDIO_CHUNK_PTS,
	AUDIO_OFFLOAD_Comm_infoType_Get_AD_Cabability,

	AUDIO_OFFLOAD_Comm_infoType_Set_1st_PreferLang,
	AUDIO_OFFLOAD_Comm_infoType_Set_2nd_PreferLang,
	AUDIO_OFFLOAD_Comm_infoType_Set_AC4_DE_Gain,
	AUDIO_OFFLOAD_Comm_infoType_Set_AC4_MD_PresentationIndex,
	AUDIO_OFFLOAD_Comm_infoType_Set_AC4_AD_PresentationIndex,

	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Get_mpegH_audioSceneConfig_valid,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Get_mpegH_audioSceneConfig_bufAddr,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Get_mpegH_audioSceneConfig_bufSize,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Set_mpegH_actionEvent,

	AUDIO_OFFLOAD_Comm_infoType_Get_SE_DTS_SRS_Version,
	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_Rx2Tx_HwPassThrough,
	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_Rx_HighBitRate,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_set_AC4_1th_pref_lang,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_set_AC4_2th_pref_lang,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_set_AC4_de_gain,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_set_AC4_MD_pres_index,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_set_AC4_AD_pres_index,
	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Decoder_Output_Fading,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_Decoder_Output_Fading,

	AUDIO_OFFLOAD_Comm_infoType_Main_Pcm_Level,
	AUDIO_OFFLOAD_Comm_infoType_Hdmi_Nonpcm_Level,
	AUDIO_OFFLOAD_Comm_infoType_Spdif_Nonpcm_Level,
	AUDIO_OFFLOAD_Comm_infoType_Cvbs_Volume,
	AUDIO_OFFLOAD_Comm_infoType_Hdmi_Volume,
	AUDIO_OFFLOAD_Comm_infoType_Spdif_Volume,
	AUDIO_OFFLOAD_Comm_infoType_Hdmi_Pcm_Mode,
	AUDIO_OFFLOAD_Comm_infoType_Spdif_Pcm_Mode,
	AUDIO_OFFLOAD_Comm_infoType_SE_Buffer_Empty_Count,

	AUDIO_OFFLOAD_Comm_infoType_Get_SE_SONICEMOTION_ABS3D_Version,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_Number_Of_PEQ_Band,
	AUDIO_OFFLOAD_Comm_infoType_Get_SE_DOLBY_DAP_Version,

	AUDIO_OFFLOAD_Comm_infoType_Set_Speaker_Configuration,
	AUDIO_OFFLOAD_Comm_infoType_Set_AC4_Language_Type,

	AUDIO_OFFLOAD_Comm_infoType_setHdmiArc_BufferProcess,
	AUDIO_OFFLOAD_Comm_infoType_Enable_AacBypass,
	AUDIO_OFFLOAD_Comm_infoType_Set_PowerDown_Depop_Duration,
	AUDIO_OFFLOAD_Comm_infoType_Set_Interrupt_To_Coprocessor,
	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_Rx_VideoMuteStatus,
	AUDIO_OFFLOAD_Comm_infoType_setSpeaker_BufferProcess,
	AUDIO_OFFLOAD_Comm_infoType_setHp_BufferProcess,
	AUDIO_OFFLOAD_Comm_infoType_setAvr_CompensationDelay,
	AUDIO_OFFLOAD_Comm_infoType_Set_Hp_Dmx_Source,
	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_Rx_InputPortType,
	AUDIO_OFFLOAD_Comm_infoType_Set_eARC_Tx_CS_WordLength,
	AUDIO_OFFLOAD_Comm_infoType_Set_eARC_Tx_CS_SPKMAP,
	AUDIO_OFFLOAD_Comm_infoType_Set_eARC_Tx_CS_Mute,
	AUDIO_OFFLOAD_Comm_infoType_Set_eARC_Tx_CS_COMPLayout,

	AUDIO_OFFLOAD_Comm_infoType_ADEC1_Decoder_Algorithm_Delay,
	AUDIO_OFFLOAD_Comm_infoType_ADEC2_Decoder_Algorithm_Delay,

	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_Rx_HWBypasseARC,

	AUDIO_OFFLOAD_Comm_infoType_Set_OMX_Output_Pcm_Mode,

	AUDIO_OFFLOAD_Comm_infoType_Get_Chip_Spec_DOLBY_Cabability,

	AUDIO_OFFLOAD_Comm_infoType_Get_HdmiNonpcmLock1,
	AUDIO_OFFLOAD_Comm_infoType_Get_HdmiNonpcmLock2,

	AUDIO_OFFLOAD_Comm_infoType_setMat_CompensationDelay,
	AUDIO_OFFLOAD_Comm_infoType_Set_TV_Tuning_Mode,
	AUDIO_OFFLOAD_Comm_infoType_Set_AAC_dialnorm,
	AUDIO_OFFLOAD_Comm_infoType_Set_Secure_Enable,

	AUDIO_OFFLOAD_Comm_infoType_AAC_Encode_Enable,
	AUDIO_OFFLOAD_Comm_infoType_LineInPowerOn,
	AUDIO_OFFLOAD_Comm_infoType_LineOutPowerOn,
	AUDIO_OFFLOAD_Comm_infoType_AdcPowerOn,
	AUDIO_OFFLOAD_Comm_infoType_DacPowerOn,
	AUDIO_OFFLOAD_Comm_infoType_cpuAudio_bEnable,
	AUDIO_OFFLOAD_Comm_infoType_Get_InitFlag,
	AUDIO_OFFLOAD_Comm_infoType_Get_kdrv_version,
	AUDIO_OFFLOAD_Comm_infoType_Get_drvAudioComm_version,
	AUDIO_OFFLOAD_Comm_infoType_ddi_version,
	AUDIO_OFFLOAD_Comm_infoType_Set_Callback,
	AUDIO_OFFLOAD_Comm_infoType_SwMixerConnect,
	AUDIO_OFFLOAD_Comm_infoType_SwMixerGain,
	AUDIO_OFFLOAD_Comm_infoType_SwMixerDdiMute,
	AUDIO_OFFLOAD_Comm_infoType_Set_pfnCaud_ExtLog,
	AUDIO_OFFLOAD_Comm_infoType_Set_pfnCaud_ExtPrint,
	AUDIO_OFFLOAD_Comm_infoType_Set_pfnCaud_ExtMonitorLog,
	AUDIO_OFFLOAD_Comm_infoType_Set_Spdif_Npcm_flag,
	AUDIO_OFFLOAD_Comm_infoType_SetHdmiAutoMute,

	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_DRAM_EMPTY_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_DRAM_UNDERRUN_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_DRAM_OVERRUN_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_BUFFER_EMPTY_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_CPU_WRITE_TRIGGER_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_LOCAL_BUFFER_INITIAL_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_LOCAL_BUFFER_LEVEL_COUNT,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_LOCAL_BUFFER_EMPTY_STATUS,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_DRAM_EMPTY_STATUS,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader1_DRAM_LEVEL_COUNT,

	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_DRAM_EMPTY_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_DRAM_UNDERRUN_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_DRAM_OVERRUN_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_BUFFER_EMPTY_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_CPU_WRITE_TRIGGER_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_LOCAL_BUFFER_INITIAL_FLAG,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_LOCAL_BUFFER_LEVEL_COUNT,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_LOCAL_BUFFER_EMPTY_STATUS,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_DRAM_EMPTY_STATUS,
	AUDIO_OFFLOAD_Comm_infoType_Get_R2DmaReader2_DRAM_LEVEL_COUNT,

	AUDIO_OFFLOAD_Comm_infoType_Set_UI_AD_Enable,
	AUDIO_OFFLOAD_Comm_infoType_Set_AC4_Prefer_Associated_Type,
	AUDIO_OFFLOAD_Comm_infoType_Set_AC4_Prefer_Associated_Type_Over_Lang,
	AUDIO_OFFLOAD_Comm_infoType_Set_UI_SPS_Enable,

	AUDIO_OFFLOAD_Comm_infoType_Set_Chip_SupportEARC,
	AUDIO_OFFLOAD_Comm_infoType_Get_HDMI_Rx_PCM_WordLength,
	AUDIO_OFFLOAD_Comm_infoType_Get_HDMI_Rx_PCM_ChCount,
	AUDIO_OFFLOAD_Comm_infoType_Get_HDMI_Rx_PCM_ChAlloc,
	AUDIO_OFFLOAD_Comm_infoType_Get_HDMI_Rx_HighBitRate,
	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_Rx_PCM_Delay,
	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_Rx_71_downmix_51,

	AUDIO_OFFLOAD_Comm_infoType_Set_Cpu_Sound_Algorithm_Delay,
	AUDIO_OFFLOAD_Comm_infoType_Set_MT_EARC_SINE_GEN,
	AUDIO_OFFLOAD_Comm_infoType_Set_Encoder_Channel_Lock,
	AUDIO_OFFLOAD_Comm_infoType_Set_Reset_Main_Path_Delay_Buffer,
	AUDIO_OFFLOAD_Comm_infoType_Get_STR_CoBuf_Base,
	AUDIO_OFFLOAD_Comm_infoType_Get_STR_CoBuf_Size,
	AUDIO_OFFLOAD_Comm_infoType_Set_LR_Swap_LineOut0,
	AUDIO_OFFLOAD_Comm_infoType_Set_LR_Swap_LineOut1,
	AUDIO_OFFLOAD_Comm_infoType_Set_LR_Swap_LineOut2,
	AUDIO_OFFLOAD_Comm_infoType_Set_LR_Swap_LineOut3,
	AUDIO_OFFLOAD_Comm_infoType_Set_LR_Swap_I2SOut0,
	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_RX_Mute_Event_Ctrl,
	AUDIO_OFFLOAD_Comm_infoType_Set_eARC_Tx_Enable,
	AUDIO_OFFLOAD_Comm_infoType_Set_DigitalTx_Off2OnTime,
	AUDIO_OFFLOAD_Comm_infoType_Set_LowLatency_BufferProcess,

	AUDIO_OFFLOAD_Comm_infoType_Get_HDMI_Rx_FrameRate,
	AUDIO_OFFLOAD_Comm_infoType_Get_ADEC1_Dra_ChannelMode,
	AUDIO_OFFLOAD_Comm_infoType_Get_ADEC2_Dra_ChannelMode,
	AUDIO_OFFLOAD_Comm_infoType_Set_EARC_Enable,
	AUDIO_OFFLOAD_Comm_infoType_Set_HDMI_Rx_NpcmDec_Reset,
	AUDIO_OFFLOAD_Comm_infoType_Set_BypassTb11Gain,
} AUDIO_OFFLOAD_Comm_infoType;

typedef enum {
	AUDIO_OFFLOAD_ParamType_SoundMode = 0,
	AUDIO_OFFLOAD_ParamType_syncSTC,
	AUDIO_OFFLOAD_ParamType_PTS_info,
	AUDIO_OFFLOAD_ParamType_setAudioDecoder,
	AUDIO_OFFLOAD_ParamType_acMode,
	AUDIO_OFFLOAD_ParamType_MM_FFx2,
	AUDIO_OFFLOAD_ParamType_reqDataSize,
	AUDIO_OFFLOAD_ParamType_esBuf_informDataRdy,
	AUDIO_OFFLOAD_ParamType_playControl,
	AUDIO_OFFLOAD_ParamType_mute,
	AUDIO_OFFLOAD_ParamType_predecode,
	AUDIO_OFFLOAD_ParamType_setWMADecParam,
	AUDIO_OFFLOAD_ParamType_setCOOKDecParam,
	AUDIO_OFFLOAD_ParamType_setXPCMDecParam,
	AUDIO_OFFLOAD_ParamType_UNI_PCM3_Input_Addr,
	AUDIO_OFFLOAD_ParamType_UNI_NEED_DECODE_FRMCNT,
	AUDIO_OFFLOAD_ParamType_UNI_ES_Wptr,
	AUDIO_OFFLOAD_ParamType_UNI_PCMOutCnt,
	AUDIO_OFFLOAD_ParamType_AllocDecoder,
	AUDIO_OFFLOAD_ParamType_FreeDecoder,
	AUDIO_OFFLOAD_ParamType_omx_spdif_mode,
	AUDIO_OFFLOAD_ParamType_omx_spdif_play,
	AUDIO_OFFLOAD_ParamType_omx_spdif_pcmLevel,
	AUDIO_OFFLOAD_ParamType_setExtSynth,
	AUDIO_OFFLOAD_ParamType_trueHD_bypass_enable,
	AUDIO_OFFLOAD_ParamType_tvos2_PCM_rdPtr,
	AUDIO_OFFLOAD_ParamType_tvos2_DTV_SyncType,
	AUDIO_OFFLOAD_ParamType_CommonCmd,
	AUDIO_OFFLOAD_ParamType_Multi_Channel,
	AUDIO_OFFLOAD_ParamType_omx_spdif_pause,
	AUDIO_OFFLOAD_ParamType_omx_spdif_flush,
	AUDIO_OFFLOAD_ParamType_omx_spdif_allowed_sampleSize,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_DRC_MODE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_DMX_MODE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_HIGH_CUT,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_LOW_BOOST,
	AUDIO_OFFLOAD_R2_SHM_PARAM_AD_Volume,
	AUDIO_OFFLOAD_R2_Set_NonPcm_Sel,
	AUDIO_OFFLOAD_ParamType_Abs_ReadReg_Target,
	AUDIO_OFFLOAD_ParamType_Abs_WriteReg_Target,
	AUDIO_OFFLOAD_ParamType_Abs_WriteReg_Value,
	AUDIO_OFFLOAD_ParamType_Abs_WriteMaskReg,
	AUDIO_OFFLOAD_ParamType_ReadDM_Target,
	AUDIO_OFFLOAD_ParamType_WriteDM_Target,
	AUDIO_OFFLOAD_ParamType_WriteDM_Value,
	AUDIO_OFFLOAD_ParamType_ReadPM_Target,
	AUDIO_OFFLOAD_ParamType_WritePM_Target,
	AUDIO_OFFLOAD_ParamType_WritePM_Value,
	AUDIO_OFFLOAD_ParamType_Abs_ReadXbox_Target,
	AUDIO_OFFLOAD_ParamType_Abs_WriteXbox_Target,
	AUDIO_OFFLOAD_ParamType_Abs_WriteXbox_Value,
	AUDIO_OFFLOAD_ParamType_AUDIO_OFFLOAD_AAC_mm_single_frame_mode,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ES_Limiter_EN,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ES_Limiter_Threshold,
	AUDIO_OFFLOAD_R2_SHM_PARAM_PCM_Limiter_EN,
	AUDIO_OFFLOAD_R2_SHM_PARAM_PCM_Limiter_Threshold,
	AUDIO_OFFLOAD_SE_Set_PCM_Capture_Volume,
	AUDIO_OFFLOAD_SE_Set_PCM_Capture2_Volume,
	AUDIO_OFFLOAD_infoType_Abs_ReadReg_Target,
	AUDIO_OFFLOAD_infoType_Abs_WriteReg_Target,
	AUDIO_OFFLOAD_infoType_Abs_WriteReg_Value,
	AUDIO_OFFLOAD_infoType_ReadDM_Target,
	AUDIO_OFFLOAD_infoType_WriteDM_Target,
	AUDIO_OFFLOAD_infoType_WriteDM_Value,
	AUDIO_OFFLOAD_infoType_ReadPM_Target,
	AUDIO_OFFLOAD_infoType_WritePM_Target,
	AUDIO_OFFLOAD_infoType_WritePM_Value,
	AUDIO_OFFLOAD_ParamType_UNI_TrickMode,
	AUDIO_OFFLOAD_ParamType_MPG_AVOFFSET,
	AUDIO_OFFLOAD_ParamType_AC3_AVOFFSET,
	AUDIO_OFFLOAD_ParamType_AAC_AVOFFSET,
	AUDIO_OFFLOAD_ParamType_SE_Set_I2S_OutNumber,
	AUDIO_OFFLOAD_ParamType_SE_Set_HP_Delay,
	AUDIO_OFFLOAD_ParamType_SE_Set_ADEC0_Input_delay,
	AUDIO_OFFLOAD_ParamType_SE_Set_ADEC1_Input_delay,
	AUDIO_OFFLOAD_ParamType_R2_Set_NonPcm_Sel,
	AUDIO_OFFLOAD_ParamType_Low_Latency_Limiter_ES_enable,
	AUDIO_OFFLOAD_ParamType_Low_Latency_Limiter_ES_Threshold,
	AUDIO_OFFLOAD_ParamType_Low_Latency_Limiter_PCM_Threshold,
	AUDIO_OFFLOAD_ParamType_Low_Latency_Limiter_PCM_Skip_Target,
	AUDIO_OFFLOAD_ParamType_ES2_IsUsedBy_Dual,
	AUDIO_OFFLOAD_ParamType_ddp_disable_atmos,
	AUDIO_OFFLOAD_ParamType_Decoder_RepeatPlay,
	AUDIO_OFFLOAD_ParamType_SetEDIDOutputInterface,
	AUDIO_OFFLOAD_ParamType_FreerunMode_Pcm_Output_Threshold_Enable,
	AUDIO_OFFLOAD_ParamType_FreerunMode_Pcm_Output_Threshold_Value,
	AUDIO_OFFLOAD_ParamType_Downmix_Mode,
	AUDIO_OFFLOAD_ParamType_DolbyDrc_Mode,
	AUDIO_OFFLOAD_ParamType_DolbyDrc_HighCutScale,
	AUDIO_OFFLOAD_ParamType_DolbyDrc_LowBootScale,
	AUDIO_OFFLOAD_ParamType_Decoder_FlushPcmFrom_PTS,
	AUDIO_OFFLOAD_ParamType_Decoder_FlushPcmFrom_Immediately,
	AUDIO_OFFLOAD_ParamType_Decoder_FlushPcmFrom_Cancel,
	AUDIO_OFFLOAD_ParamType_Decoder_FlushPcmUntil_PTS,
	AUDIO_OFFLOAD_ParamType_Decoder_FlushPcmUntil_Immediately,
	AUDIO_OFFLOAD_ParamType_Decoder_FlushPcmUntil_Cancel,
	AUDIO_OFFLOAD_ParamType_Decoder_FlushPcm_PTS_Tolerance,
	AUDIO_OFFLOAD_ParamType_PUSI_Enable,
	AUDIO_OFFLOAD_ParamType_Spdif_RDptr,
	AUDIO_OFFLOAD_ParamType_omx_pcm3_pcmLevel,
	AUDIO_OFFLOAD_ParamType_omx_spdif_flush_en,
	AUDIO_OFFLOAD_ParamType_MPEG_Decoder_Delay,
	AUDIO_OFFLOAD_ParamType_AAC_Decoder_Delay,
	AUDIO_OFFLOAD_ParamType_AC3_Decoder_Delay,
	AUDIO_OFFLOAD_ParamType_AC4_Decoder_Delay,
	AUDIO_OFFLOAD_ParamType_Tempo_Enable,
	AUDIO_OFFLOAD_ParamType_Tempo_PlayRate,
	AUDIO_OFFLOAD_ParamType_DTS_Cert_Seamless_Mode,
	AUDIO_OFFLOAD_ParamType_omx_atmos_valid,
	AUDIO_OFFLOAD_ParamType_Speaker_With_AD_Enable,
	AUDIO_OFFLOAD_ParamType_Headphone_With_AD_Enable,
	AUDIO_OFFLOAD_ParamType_Decoder_Delay,
	AUDIO_OFFLOAD_ParamType_Decoder_ApplyPanFade_Enable,
	AUDIO_OFFLOAD_ParamType_Low_Latency_Limiter_PCM_Enable,
	AUDIO_OFFLOAD_ParamType_PTS_OFFSET,
	AUDIO_OFFLOAD_ParamType_Sys_Sound_Mix_Before_Dap,
	AUDIO_OFFLOAD_ParamType_AvSync_Freerun_Tolerance_Enable,
	AUDIO_OFFLOAD_ParamType_AvSync_Freerun_Tolerance_Value,
	AUDIO_OFFLOAD_ParamType_PTS_GAP_Fade_Enable,
	AUDIO_OFFLOAD_ParamType_PTS_GAP_Fade_Threshold,
	AUDIO_OFFLOAD_ParamType_Vorbis_Oggm_Mode,
	AUDIO_OFFLOAD_ParamType_debugLevel,
	AUDIO_OFFLOAD_ParamType_MM_dropAudio_to_assigned_PTS,

	AUDIO_OFFLOAD_ParamType_uiInfoXml_gotCnt,
	AUDIO_OFFLOAD_ParamType_uiActionXml_sentCnt,
	AUDIO_OFFLOAD_ParamType_uiActionXml_addr,
	AUDIO_OFFLOAD_ParamType_uiActionXml_size,
	AUDIO_OFFLOAD_ParamType_uiActionXml_flag,
	AUDIO_OFFLOAD_ParamType_dgo_bypass_avsync_tolerance,

	AUDIO_OFFLOAD_ParamType_MM_TS_PTS_WITH_MSB,
	AUDIO_OFFLOAD_ParamType_STR_Resume,
	AUDIO_OFFLOAD_ParamType_Hdmi_RDptr,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ES_WR_PTR,
	AUDIO_OFFLOAD_R2_SHM_PARAM_MPG_AVOFFSET,
	AUDIO_OFFLOAD_R2_SHM_PARAM_AC3_AVOFFSET,
	AUDIO_OFFLOAD_R2_SHM_PARAM_AAC_AVOFFSET,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_GAIN,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_MULTI_FRAME_HEADER,
	AUDIO_OFFLOAD_R2_SHM_PARAM_MM_TS_SYNC_STC,
	AUDIO_OFFLOAD_R2_SHM_PARAM_MM_FF2X,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DECODE_MUTE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_SOUND_MODE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_MM_FILE_REQ_SIZE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_MM_INPUT_PTS,
	AUDIO_OFFLOAD_R2_SHM_PARAM_UNI_PCM_SET_OUTPUT_CNT,
	AUDIO_OFFLOAD_R2_SHM_PARAM_UNI_SETUP_DECODE_FRMCNT,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ES2_WR_PTR,
	AUDIO_OFFLOAD_R2_SHM_PARAM_OMX_SPDIF_CTRL,
	AUDIO_OFFLOAD_R2_SHM_PARAM_OMX_SPDIF_PCM_LEVEL,
	AUDIO_OFFLOAD_R2_SHM_PARAM_MPEG_SOUNDMODE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_MPEG_GAIN,
	AUDIO_OFFLOAD_R2_SHM_PARAM_COOK_NUMCODECS,
	AUDIO_OFFLOAD_R2_SHM_PARAM_COOK_SAMPLES,
	AUDIO_OFFLOAD_R2_SHM_PARAM_COOK_SAMPLERATES,
	AUDIO_OFFLOAD_R2_SHM_PARAM_COOK_CHANNELS,
	AUDIO_OFFLOAD_R2_SHM_PARAM_COOK_REGIONS,
	AUDIO_OFFLOAD_R2_SHM_PARAM_COOK_CPLSTART,
	AUDIO_OFFLOAD_R2_SHM_PARAM_COOK_CPLQBITS,
	AUDIO_OFFLOAD_R2_SHM_PARAM_COOK_FRAMESIZE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DTS_DMX_LFE_ENABLE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DTS_DMX_MODE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DTS_SEAMLESS_MODE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_VERSION,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_CHANNELS,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_SAMPLERATE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_BYTERATE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_BLOCKALIGN,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_ENCOPT,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_PARSINGBYAPP,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_BITS_PER_SAMPLE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_CHANNELMASK,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_DRC_PARAM_EXIST,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_DRC_RMS_AMP_REF,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_DRC_RMS_AMP_TARGET,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_DRC_PEAK_AMP_REF,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_DRC_PEAK_AMP_TARGET,
	AUDIO_OFFLOAD_R2_SHM_PARAM_ASF_MAX_PACKET_SIZE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_XPCM_TYPE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_XPCM_CHANNELS,
	AUDIO_OFFLOAD_R2_SHM_PARAM_XPCM_SAMPLERATES,
	AUDIO_OFFLOAD_R2_SHM_PARAM_XPCM_BITS_PER_SAMPLE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_XPCM_BLOCK_SIZE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_XPCM_SAMPLE_PER_BLOCK,
	AUDIO_OFFLOAD_R2_SHM_PARAM_HASH_KEY,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DPGA_FLAG,
	AUDIO_OFFLOAD_SE_Set_I2S_OutNumber,
	AUDIO_OFFLOAD_SE_Set_HP_Delay,
	AUDIO_OFFLOAD_SE_Set_AENC_Input_Mux,
	AUDIO_OFFLOAD_SE_Set_AENC_Mute,
	AUDIO_OFFLOAD_SE_Set_ADEC0_Input_delay,
	AUDIO_OFFLOAD_SE_Set_ADEC1_Input_delay,
	AUDIO_OFFLOAD_ParamType_KillProcess,
	AUDIO_OFFLOAD_ParamType_bEnableKernelMsg,
	AUDIO_OFFLOAD_ParamType_PreNotMM_Flag,
	AUDIO_OFFLOAD_ParamType_TrickPlay,
	AUDIO_OFFLOAD_Set_DMA_Buffer_Limiter,
	AUDIO_OFFLOAD_ParamType_omx_spdif_mute,
	AUDIO_OFFLOAD_ParamType_omx_OutputDelayOffset_bEnable,
	AUDIO_OFFLOAD_ParamType_omx_is_RTC,
	AUDIO_OFFLOAD_ParamType_TV_Service_bForeground,
	AUDIO_OFFLOAD_ParamType_Optical_Output_AC3P_Enable,
	AUDIO_OFFLOAD_ParamType_Optical_Output_Half_Auto,
	AUDIO_OFFLOAD_ParamType_MultiCH_Delay,
	AUDIO_OFFLOAD_ParamType_MetaData_Select,
	AUDIO_OFFLOAD_ParamType_DMXLR_Mixed_Channel,
	AUDIO_OFFLOAD_ParamType_System_Sound_Mixed_Channel,
	AUDIO_OFFLOAD_ParamType_HDMI_RX_Unstable_Mute,
	AUDIO_OFFLOAD_ParamType_HDMI_RX_Unstable_Threshold,
	AUDIO_OFFLOAD_ParamType_HDMI_RX_Unstable_Mute_Duration_CH5,
	AUDIO_OFFLOAD_ParamType_HDMI_RX_Unstable_Mute_Duration_CH6,
	AUDIO_OFFLOAD_ParamType_HDMI_Event_Mute_Enable,
	AUDIO_OFFLOAD_ParamType_bEnableEncChmodLock,
	AUDIO_OFFLOAD_ParamType_bEnableAtmosLocking,
	AUDIO_OFFLOAD_ParamType_Optical_Output_AAC_Encode,
	AUDIO_OFFLOAD_ParamType_Enable_Set_Luxgen_Se3_Path0_Param,
	AUDIO_OFFLOAD_ParamType_Enable_Set_Luxgen_Se3_Path1_Param,
	AUDIO_OFFLOAD_ParamType_bReg_Backstrace,
	AUDIO_OFFLOAD_ParamType_EnableDynamicSetEsBufId,
	AUDIO_OFFLOAD_ParamType_MainAdecEsId,
	AUDIO_OFFLOAD_ParamType_AdAdecEsId,
	AUDIO_OFFLOAD_ParamType_SetAencBaseTime,
	AUDIO_OFFLOAD_ParamType_SetCapture0Delay,
	AUDIO_OFFLOAD_ParamType_SetCapture1Delay,
	AUDIO_OFFLOAD_ParamType_SetCapture2Delay,
	AUDIO_OFFLOAD_ParamType_SetDumpPcm,
	AUDIO_OFFLOAD_ParamType_AUDIOOpen,
	AUDIO_OFFLOAD_ParamType_AUDIOClose,
	AUDIO_OFFLOAD_ParamType_SysTime_CheckPoint,

	AUDIO_OFFLOAD_ParamType_Detect_Beep_STC_Enable,

	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_DAP_DRC_MODE,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_HIGH_CUT_MULTI_CHANNEL,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_LOW_BOOST_MULTI_CHANNEL,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_ENC_CHMOD_LOCK,
	AUDIO_OFFLOAD_R2_SHM_PARAM_DOLBY_DDPENC_ATMOS_LOCK,
	AUDIO_OFFLOAD_ParamType_AVR_CapabilityChange,
	AUDIO_OFFLOAD_ParamType_PARSER_DMA_SELECT,
	AUDIO_OFFLOAD_ParamType_SetDdpBypassDelay,
	AUDIO_OFFLOAD_ParamType_TS_PARSER_ES_NONBLOCKING,
	AUDIO_OFFLOAD_ParamType_PUSH_TLV_TABLE,
	AUDIO_OFFLOAD_ParamType_MAX,
} AUDIO_OFFLOAD_ParamType;

typedef enum {
	AUDIO_OFFLOAD_infoType_Unknown = -1,
	AUDIO_OFFLOAD_infoType_DecStatus = 0,
	AUDIO_OFFLOAD_infoType_SampleRate,
	AUDIO_OFFLOAD_infoType_SoundMode,
	AUDIO_OFFLOAD_infoType_capability,
	AUDIO_OFFLOAD_infoType_AudioSyncStatus,
	AUDIO_OFFLOAD_infoType_bitRate,
	AUDIO_OFFLOAD_infoType_acmod,
	AUDIO_OFFLOAD_infoType_okFrmCnt,
	AUDIO_OFFLOAD_infoType_errFrmCnt,
	AUDIO_OFFLOAD_infoType_1ms_timeStamp,
	AUDIO_OFFLOAD_infoType_33bit_PTS		  = 10,
	AUDIO_OFFLOAD_infoType_33bit_STCPTS_DIFF,
	AUDIO_OFFLOAD_infoType_esBuf_req,
	AUDIO_OFFLOAD_infoType_BufferSize,
	AUDIO_OFFLOAD_infoType_BufferAddr,
	AUDIO_OFFLOAD_infoType_esBuf_currLevel,
	AUDIO_OFFLOAD_infoType_pcmBuf_currLevel,
	AUDIO_OFFLOAD_infoType_get_audio_filter,
	AUDIO_OFFLOAD_infoType_audio_unsupported,
	AUDIO_OFFLOAD_infoType_getDecInfo1,
	AUDIO_OFFLOAD_infoType_UNI_PCM1_Info	  = 20,
	AUDIO_OFFLOAD_infoType_UNI_PCM3_Level,
	AUDIO_OFFLOAD_infoType_UNI_ES_Level,
	AUDIO_OFFLOAD_infoType_UNI_ES_Base,
	AUDIO_OFFLOAD_infoType_UNI_ES_Size,
	AUDIO_OFFLOAD_infoType_UNI_PCM_Base,
	AUDIO_OFFLOAD_infoType_UNI_PCM_Size,
	AUDIO_OFFLOAD_infoType_Decoder_ID,
	AUDIO_OFFLOAD_infoType_AccumEsCnt,
	AUDIO_OFFLOAD_infoType_MadBaseAddr,
	AUDIO_OFFLOAD_infoType_hashkey,
	AUDIO_OFFLOAD_infoType_UNI_PCM3_Base,
	AUDIO_OFFLOAD_infoType_UNI_PCM3_Size,
	AUDIO_OFFLOAD_infoType_AC3_BSID,
	AUDIO_OFFLOAD_infoType_get_trueHD_bypass_enable,
	AUDIO_OFFLOAD_infoType_syncSTC_in_mmTs,
	AUDIO_OFFLOAD_infoType_Pcm_Output_Channel,
	AUDIO_OFFLOAD_infoType_PCM_LEVEL,
	AUDIO_OFFLOAD_infoType_DEC_STAUS,
	AUDIO_OFFLOAD_infoType_CURR_PTS,
	AUDIO_OFFLOAD_infoTypeO_TP_ES_FreeSize,
	AUDIO_OFFLOAD_infoType_Abs_ReadReg,
	AUDIO_OFFLOAD_infoType_ReadDM_Value,
	AUDIO_OFFLOAD_infoType_ReadPM_Value,
	AUDIO_OFFLOAD_infoType_Abs_ReadXbox,
	AUDIO_OFFLOAD_infoType_omx_no_mixing,
	AUDIO_OFFLOAD_infoType_omx_ES_bypass,
	AUDIO_OFFLOAD_infoType_Decoder,
	AUDIO_OFFLOAD_infoType_Decoder_Type,
	AUDIO_OFFLOAD_infoType_33bit_latestPTS,
	AUDIO_OFFLOAD_infoType_tvos2_PCM1_Info,
	AUDIO_OFFLOAD_infoType_tvos2_pcm_rdpt,
	AUDIO_OFFLOAD_infoType_tvos2_pcm_wrpt,
	AUDIO_OFFLOAD_infoType_tvos2_cpts,
	AUDIO_OFFLOAD_infoType_tvos2_pcm_framesize,
	AUDIO_OFFLOAD_infoType_Dec_Channel_Mode,
	AUDIO_OFFLOAD_infoType_DRA_Channel_Mapping,
	AUDIO_OFFLOAD_infoType_Smp_Rate,
	AUDIO_OFFLOAD_infoType_Bit_Rate,
	AUDIO_OFFLOAD_infoType_DOLBY_BS_Mode,
	AUDIO_OFFLOAD_infoType_DOLBY_AAC_type,
	AUDIO_OFFLOAD_infoType_DTS_CD_Mode,
	AUDIO_OFFLOAD_infoType_DTS_PCM_Frame_Size,
	AUDIO_OFFLOAD_infoType_DTS_ES_Type,
	AUDIO_OFFLOAD_infoType_DTS_T1CC_Flag,
	AUDIO_OFFLOAD_infoType_SPDIF_info_flag,
	AUDIO_OFFLOAD_infoType_MPEG_Layer,
	AUDIO_OFFLOAD_infoType_MPEG_Stereo_Mode,
	AUDIO_OFFLOAD_infoType_MPEG_Header,
	AUDIO_OFFLOAD_infoType_DUMMY1,
	AUDIO_OFFLOAD_infoType_DUMMY2,
	AUDIO_OFFLOAD_infoType_DUMMY3,
	AUDIO_OFFLOAD_infoType_get_parser_info,
	AUDIO_OFFLOAD_infoType_Is_Audio_Sync,
	AUDIO_OFFLOAD_infoType_Get_DDPEnc_Status,
	AUDIO_OFFLOAD_infoType_Is_DDP_8ch_Stream,
	AUDIO_OFFLOAD_infoType_Decoder_FlushPcm_PTS_Tolerance,
	AUDIO_OFFLOAD_infoType_ADEC1_Ok_Frame_Count,
	AUDIO_OFFLOAD_infoType_ADEC1_Error_Frame_Count,
	AUDIO_OFFLOAD_infoType_ADEC1_Skip_Frame_Count,
	AUDIO_OFFLOAD_infoType_ADEC1_Repeat_Frame_Count,
	AUDIO_OFFLOAD_infoType_ADEC1_Play_Cmd,
	AUDIO_OFFLOAD_infoType_ADEC1_Codec_Type,
	AUDIO_OFFLOAD_infoType_Decoder_Pcm_Size,
	AUDIO_OFFLOAD_infoType_Decoder_Pcm_Pts,
	AUDIO_OFFLOAD_infoType_Decoder_Pcm_Buffer_Info,
	AUDIO_OFFLOAD_infoType_Is_Atmos_Stream,
	AUDIO_OFFLOAD_infoType_Is_Atmos_Stream_FW_flag,
	AUDIO_OFFLOAD_infoType_Decoder_Delay,
	AUDIO_OFFLOAD_infoType_Decoder_Es_Size,
	AUDIO_OFFLOAD_infoType_Decoder_Es_Pts,
	AUDIO_OFFLOAD_infoType_Decoder_Es_Buffer_Info,
	AUDIO_OFFLOAD_infoType_Spdif_WRptr,
	AUDIO_OFFLOAD_infoType_Decoder_Channel_Mapping,
	AUDIO_OFFLOAD_infoType_AAC_Header_Type,
	AUDIO_OFFLOAD_infoType_Atmos_Notification,
	AUDIO_OFFLOAD_infoType_HDMI_Encoder_Path_Latency,
	AUDIO_OFFLOAD_infoType_SPDIF_Encoder_Path_Latency,
	AUDIO_OFFLOAD_infoType_Decoder_OutputPcm_Flag,
	AUDIO_OFFLOAD_infoType_Vorbis_Oggm_Capability,
	AUDIO_OFFLOAD_infoType_Encoder_Path_minimum_Latency,
	AUDIO_OFFLOAD_infoType_syncMissCnt,
	AUDIO_OFFLOAD_infoType_adecR2_uart_buf_base,
	AUDIO_OFFLOAD_infoType_adecR2_uart_buf_size,
	AUDIO_OFFLOAD_infoType_adecR2_uart_buf_wptr,
	AUDIO_OFFLOAD_infoType_asndR2_uart_buf_base,
	AUDIO_OFFLOAD_infoType_asndR2_uart_buf_size,
	AUDIO_OFFLOAD_infoType_asndR2_uart_buf_wptr,

	AUDIO_OFFLOAD_infoType_uiActionXml_gotCnt,
	AUDIO_OFFLOAD_infoType_uiInfoXml_sentCnt,
	AUDIO_OFFLOAD_infoType_uiInfoXml_addr,
	AUDIO_OFFLOAD_infoType_uiInfoXml_size,
	AUDIO_OFFLOAD_infoType_uiInfoXml_flag,

	AUDIO_OFFLOAD_infoType_Speaker_Path_Latency,
	AUDIO_OFFLOAD_infoType_Headphone_Path_Latency,
	AUDIO_OFFLOAD_infoType_HDMI_PCM_Path_Latency,
	AUDIO_OFFLOAD_infoType_SPDIF_PCM_Path_Latency,
	AUDIO_OFFLOAD_infoType_64bit_PTS,
	AUDIO_OFFLOAD_infoType_Speaker_minimum_Latency,

	AUDIO_OFFLOAD_infoType_Is_Atmos,
	AUDIO_OFFLOAD_infoType_MMTsSyncFlag,
	AUDIO_OFFLOAD_infoType_STR_Resume,
	AUDIO_OFFLOAD_infoType_SMP_RATE,
	AUDIO_OFFLOAD_infoType_BIT_RATE,
	AUDIO_OFFLOAD_infoType_PCM_SIZE,
	AUDIO_OFFLOAD_infoType_spdifbuf_LEVEL,
	AUDIO_OFFLOAD_infoType_spdifbuf_WR_PTR,
	AUDIO_OFFLOAD_infoType_DOLBY_DEC_TYPE,
	AUDIO_OFFLOAD_infoType_DOLBY_FRAME_SIZE,
	AUDIO_OFFLOAD_infoType_DOLBY_BS_MODE,
	AUDIO_OFFLOAD_infoType_DOLBY_AAC_TYPE,
	AUDIO_OFFLOAD_infoType_DTS_CD_MODE,
	AUDIO_OFFLOAD_infoType_DTS_PCM_FRAME_SIZE,
	AUDIO_OFFLOAD_infoType_DTS_ES_TYPE,
	AUDIO_OFFLOAD_infoType_MPEG_LAYER,
	AUDIO_OFFLOAD_infoType_MPEG_STEREOMODE,
	AUDIO_OFFLOAD_infoType_MPEG_HEADER,
	AUDIO_OFFLOAD_infoType_SE_SPEAKER_MUTE_STATUS,
	AUDIO_OFFLOAD_infoType_SE_HPOUT_MUTE_STATUS,
	AUDIO_OFFLOAD_infoType_SE_SPDIFOUT_MUTE_STATUS,
	AUDIO_OFFLOAD_infoType_SE_SCARTOUT_MUTE_STATUS,
	AUDIO_OFFLOAD_infoType_SE_Decoder_Delay,
	AUDIO_OFFLOAD_infoType_SE_SpeakerOut_Delay,
	AUDIO_OFFLOAD_infoType_SE_HpOut_Delay,
	AUDIO_OFFLOAD_infoType_SE_SPDIFOut_Delay,
	AUDIO_OFFLOAD_infoType_R2_Dec_Type,
	AUDIO_OFFLOAD_infoType_PreNotMM_Flag,
	AUDIO_OFFLOAD_infoType_omx_OutputDelayOffset_bEnable,
	AUDIO_OFFLOAD_infoType_omx_is_RTC,
	AUDIO_OFFLOAD_infoType_TV_Service_bForeground,
	AUDIO_OFFLOAD_infoType_HDMI_NPCM_Lock_Status,
	AUDIO_OFFLOAD_infoType_MetaData_Select,
	AUDIO_OFFLOAD_infoType_DMXLR_Mixed_Channel,
	AUDIO_OFFLOAD_infoType_System_Sound_Mixed_Channel,
	AUDIO_OFFLOAD_infoType_Multi_Pcm_WRptr,
	AUDIO_OFFLOAD_infoType_ARC_MUTE_STATUS,
	AUDIO_OFFLOAD_infoType_ARCOut_Delay,
	AUDIO_OFFLOAD_infoType_EnableDynamicSetEsBufId,
	AUDIO_OFFLOAD_infoType_MainAdecEsId,
	AUDIO_OFFLOAD_infoType_AdAdecEsId,
	AUDIO_OFFLOAD_infoType_FirstSwMixerId,
	AUDIO_OFFLOAD_infoType_PTS_GAP_Fade_Threshold,
	AUDIO_OFFLOAD_infoType_DecodedAudioFormat,
	AUDIO_OFFLOAD_infoType_STC,
	AUDIO_OFFLOAD_infoType_PcmCapture0Delay,
	AUDIO_OFFLOAD_infoType_PcmCapture1Delay,
	AUDIO_OFFLOAD_infoType_PcmCapture2Delay,
	AUDIO_OFFLOAD_infoType_AtvStandard,
	AUDIO_OFFLOAD_infoType_HdmiRxHbrFlag,
	AUDIO_OFFLOAD_infoType_AI_Sound_enable,
	AUDIO_OFFLOAD_infoType_AUDIOOpen,
	AUDIO_OFFLOAD_infoType_AUDIOClose,
	AUDIO_OFFLOAD_infoType_SysTime_CheckPoint,
	AUDIO_OFFLOAD_infoType_CommonCmd,

	AUDIO_OFFLOAD_infoType_Get_Beep_STC,

	AUDIO_OFFLOAD_infoType_Mat_Stream_Type,
	AUDIO_OFFLOAD_infoType_elapsedDecodedTime,
	AUDIO_OFFLOAD_infoType_64bit_STC,
	AUDIO_OFFLOAD_infoType_64bit_TD,
	AUDIO_OFFLOAD_infoType_Mpegh_Stream_Type,
	AUDIO_OFFLOAD_infoType_MMsyncSTC_MUTE_DONE,
	AUDIO_OFFLOAD_infoType_AacMpegVersion,
	AUDIO_OFFLOAD_infoType_Ac4DialogueEnhancementMaxGain,
} AUDIO_OFFLOAD_InfoType;

typedef enum {
	AUDIO_OFFLOAD_SIF_CMD_SET_STOP				   = 0x00,
	AUDIO_OFFLOAD_SIF_CMD_SET_PLAY				   = 0x01,
	AUDIO_OFFLOAD_SIF_CMD_ENABLE_HIDEV			   = 0x02,
	AUDIO_OFFLOAD_SIF_CMD_SET_HIDEV_FILTER_BW_LEVEL	 = 0x03,
	AUDIO_OFFLOAD_SIF_CMD_RESET_FC_TRACKING		  = 0x04,
	AUDIO_OFFLOAD_SIF_CMD_ENABLE_FC_TRACKING		 = 0x05,
	AUDIO_OFFLOAD_SIF_CMD_SET_ADC_FROM_VIF_PATH	  = 0x06,
	AUDIO_OFFLOAD_SIF_CMD_ENABLE_AUTO_MUTE		   = 0x07,
	AUDIO_OFFLOAD_SIF_CMD_ENABLE_BEEPER_FUNCTION	 = 0x08,
	AUDIO_OFFLOAD_SIF_CMD_SET_BEEPER_TONE			= 0x09,
	AUDIO_OFFLOAD_SIF_CMD_ENABLE_AGC				 = 0x0A,
	AUDIO_OFFLOAD_SIF_CMD_RESET_AGC				  = 0x0B,
	AUDIO_OFFLOAD_SIF_STANDARD_RESET				 = 0x0C,
	AUDIO_OFFLOAD_SIF_CMD_DETECT_MAIN_STD_ONLY	   = 0x0D,
	AUDIO_OFFLOAD_SIF_CMD_ENABLE_AUTO_SOUNDMODE	  = 0x0E,
	AUDIO_OFFLOAD_SIF_CMD_FMTX_SET_PREEMP			= 0x0F,
	AUDIO_OFFLOAD_SIF_CMD_SET_ENC_CMD				= 0x10,
	AUDIO_OFFLOAD_SIF_CMD_SET_ENC_Input_attenuation	 = 0x11,
	AUDIO_OFFLOAD_SIF_CMD_SET_ENC_Output_scaling	 = 0x12,
	AUDIO_OFFLOAD_SIF_CMD_SET_BTSC_Enc_M_Gain		= 0x13,
	AUDIO_OFFLOAD_SIF_CMD_SET_BTSC_Enc_D_Gain		= 0x14,
	AUDIO_OFFLOAD_SIF_CMD_SET_BTSC_Enc_SAP_Gain	  = 0x15,
	AUDIO_OFFLOAD_SIF_CMD_SET_FM_CH2_FILTER_BW_LEVEL = 0x16,
	AUDIO_OFFLOAD_SIF_CMD_SET_EU_MODE				= 0x17,

	AUDIO_OFFLOAD_SIF_CMD_GET_PAL_SC1_AMP_CMD		= 0x20,
	AUDIO_OFFLOAD_SIF_CMD_GET_PAL_SC1_NSR_CMD		= 0x21,
	AUDIO_OFFLOAD_SIF_CMD_GET_PAL_SC2_AMP_CMD		= 0x22,
	AUDIO_OFFLOAD_SIF_CMD_GET_PAL_SC2_NSR_CMD		= 0x23,
	AUDIO_OFFLOAD_SIF_CMD_GET_PAL_PILOT_VALUE		= 0x24,
	AUDIO_OFFLOAD_SIF_CMD_GET_PAL_PILOT_PHASE		= 0x25,
	AUDIO_OFFLOAD_SIF_CMD_GET_PAL_STEREO_DUAL_ID	 = 0x26,
	AUDIO_OFFLOAD_SIF_CMD_GET_PAL_NICAM_PHASE_ERR	= 0x27,

	AUDIO_OFFLOAD_SIF_CMD_GET_BTSC_SC1_AMP_CMD	   = 0x30,
	AUDIO_OFFLOAD_SIF_CMD_GET_BTSC_SC1_NSR_CMD	   = 0x31,
	AUDIO_OFFLOAD_SIF_CMD_GET_BTSC_STEREO_PILOT_AMP	 = 0x32,
	AUDIO_OFFLOAD_SIF_CMD_GET_BTSC_SAP_AMP		   = 0x33,
	AUDIO_OFFLOAD_SIF_CMD_GET_BTSC_SAP_NSR		   = 0x34,

	AUDIO_OFFLOAD_SIF_CMD2_ADC_VIA_VIF_PIN = 0x01
} AUDIO_OFFLOAD_SIF_CmdType;

typedef enum {
	AUDIO_OFFLOAD_SIF_PAL_MONO,
	AUDIO_OFFLOAD_SIF_PAL_HIDEV,
	AUDIO_OFFLOAD_SIF_PAL_A2,
	AUDIO_OFFLOAD_SIF_PAL_NICAM
} AUDIO_OFFLOAD_SIF_PAL_TYPE;

typedef enum {
	AUDIO_OFFLOAD_AUDIOSTANDARD_BG		  = 0x00,
	AUDIO_OFFLOAD_AUDIOSTANDARD_BG_A2	   = 0x01,
	AUDIO_OFFLOAD_AUDIOSTANDARD_BG_NICAM	= 0x02,
	AUDIO_OFFLOAD_AUDIOSTANDARD_I		   = 0x03,
	AUDIO_OFFLOAD_AUDIOSTANDARD_DK		  = 0x04,
	AUDIO_OFFLOAD_AUDIOSTANDARD_DK1_A2	  = 0x05,
	AUDIO_OFFLOAD_AUDIOSTANDARD_DK2_A2	  = 0x06,
	AUDIO_OFFLOAD_AUDIOSTANDARD_DK3_A2	  = 0x07,
	AUDIO_OFFLOAD_AUDIOSTANDARD_DK_NICAM	= 0x08,
	AUDIO_OFFLOAD_AUDIOSTANDARD_L		   = 0x09,
	AUDIO_OFFLOAD_AUDIOSTANDARD_M		   = 0x0A,
	AUDIO_OFFLOAD_AUDIOSTANDARD_M_BTSC	  = 0x0B,
	AUDIO_OFFLOAD_AUDIOSTANDARD_M_A2		= 0x0C,
	AUDIO_OFFLOAD_AUDIOSTANDARD_M_EIA_J	 = 0x0D,
	AUDIO_OFFLOAD_AUDIOSTANDARD_NOTSTANDARD = 0x0F
} AUDIO_OFFLOAD_SIF_STANDARD_TYPE;

typedef enum {
	AUDIO_OFFLOAD_AUDIOMODE_INVALID	  = 0x00,
	AUDIO_OFFLOAD_AUDIOMODE_MONO		 = 0x01,
	AUDIO_OFFLOAD_AUDIOMODE_FORCED_MONO	 = 0x02,
	AUDIO_OFFLOAD_AUDIOMODE_G_STEREO	 = 0x03,
	AUDIO_OFFLOAD_AUDIOMODE_K_STEREO	 = 0x04,
	AUDIO_OFFLOAD_AUDIOMODE_MONO_SAP	 = 0x05,
	AUDIO_OFFLOAD_AUDIOMODE_STEREO_SAP	 = 0x06,
	AUDIO_OFFLOAD_AUDIOMODE_DUAL_A	   = 0x07,
	AUDIO_OFFLOAD_AUDIOMODE_DUAL_B	   = 0x08,
	AUDIO_OFFLOAD_AUDIOMODE_DUAL_AB	  = 0x09,
	AUDIO_OFFLOAD_AUDIOMODE_NICAM_MONO	 = 0x0A,
	AUDIO_OFFLOAD_AUDIOMODE_NICAM_STEREO = 0x0B,
	AUDIO_OFFLOAD_AUDIOMODE_NICAM_DUAL_A = 0x0C,
	AUDIO_OFFLOAD_AUDIOMODE_NICAM_DUAL_B = 0x0D,
	AUDIO_OFFLOAD_AUDIOMODE_NICAM_DUAL_AB = 0x0E,
	AUDIO_OFFLOAD_AUDIOMODE_HIDEV_MONO	 = 0x0F,
	AUDIO_OFFLOAD_AUDIOMODE_LEFT_LEFT	= 0x10,
	AUDIO_OFFLOAD_AUDIOMODE_RIGHT_RIGHT	 = 0x11,
	AUDIO_OFFLOAD_AUDIOMODE_LEFT_RIGHT	 = 0x12
} AUDIO_OFFLOAD_SIF_AUDIOMODE_TYPE;

typedef enum {
	AUDIO_OFFLOAD_STATE_AUDIO_NO_CARRIER		   = 0x00,
	AUDIO_OFFLOAD_STATE_AUDIO_PRIMARY_CARRIER	  = 0x01,
	AUDIO_OFFLOAD_STATE_AUDIO_SECONDARY_CARRIER	= 0x02,
	AUDIO_OFFLOAD_STATE_AUDIO_NICAM				= 0x04,
	AUDIO_OFFLOAD_STATE_AUDIO_STEREO			   = 0x08,
	AUDIO_OFFLOAD_STATE_AUDIO_BILINGUAL			= 0x10,
	AUDIO_OFFLOAD_STATE_AUDIO_PILOT				= 0x20,
	AUDIO_OFFLOAD_STATE_AUDIO_DK2				  = 0x40,
	AUDIO_OFFLOAD_STATE_AUDIO_DK3				  = 0x80
} AUDIO_OFFLOAD_SIF_AUDIOSTATUS;

typedef enum {
	AUDIO_OFFLOAD_PRESCALE_STEP_ONE_DB				  = 0x04,
	AUDIO_OFFLOAD_SET_PRESCALE_A2_FM				  = 0x00,
	AUDIO_OFFLOAD_SET_PRESCALE_NICAM				  = 0x01,
	AUDIO_OFFLOAD_SET_PRESCALE_AM					  = 0x02,
	AUDIO_OFFLOAD_SET_PRESCALE_HIDEV				  = 0x03,
	AUDIO_OFFLOAD_SET_PRESCALE_FM_M					  = 0x04,
	AUDIO_OFFLOAD_SET_PRESCALE_HIDEV_M				  = 0x05,

	AUDIO_OFFLOAD_SET_PRESCALE_BTSC					  = 0x00,
	AUDIO_OFFLOAD_SET_PRESCALE_BTSC_MONO			  = 0x01,
	AUDIO_OFFLOAD_SET_PRESCALE_BTSC_STEREO			  = 0x02,
	AUDIO_OFFLOAD_SET_PRESCALE_BTSC_SAP				  = 0x03,

	AUDIO_OFFLOAD_SET_PRESCALE_FM_RADIO				  = 0x00,
	AUDIO_OFFLOAD_SET_PRESCALE_FM_RADIO_MONO		  = 0x01,
	AUDIO_OFFLOAD_SET_PRESCALE_FM_RADIO_STEREO		  = 0x02
} AUDIO_OFFLOAD_SIF_GAIN_TYPE;

typedef enum {
	AUDIO_OFFLOAD_SPDIF_OUT_PCM					 = 0x0,
	AUDIO_OFFLOAD_SPDIF_OUT_AUTO				 = 0x2,
	AUDIO_OFFLOAD_SPDIF_OUT_BYPASS,
	AUDIO_OFFLOAD_SPDIF_OUT_TRANSCODE,
} AUDIO_OFFLOAD_SPDIF_OUTPUT_TYPE;

typedef enum {
	AUDIO_OFFLOAD_SPDIF_CS_CategoryCode			   = 0x0,
	AUDIO_OFFLOAD_SPDIF_CS_CopyRight				  = 0x1,
	AUDIO_OFFLOAD_SPDIF_CS_SourceNumber			   = 0x2,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber			  = 0x3,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq					= 0x4,
	AUDIO_OFFLOAD_SPDIF_CS_ClockAcc				   = 0x5,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelAB					 = 0x6,
	AUDIO_OFFLOAD_SPDIF_CS_CopyProtect				= 0x7,
} AUDIO_OFFLOAD_SPDIF_CS_TYPE;

typedef enum {
	AUDIO_OFFLOAD_SPDIF_CS_Category_BroadCast		 = 0x00,
	AUDIO_OFFLOAD_SPDIF_CS_Category_General		   = 0x01,
	AUDIO_OFFLOAD_SPDIF_CS_Category_BroadCast_JP	  = 0x02,
	AUDIO_OFFLOAD_SPDIF_CS_Category_BroadCast_EU	  = 0x03,
	AUDIO_OFFLOAD_SPDIF_CS_Category_BroadCast_USA	 = 0x04,
	AUDIO_OFFLOAD_SPDIF_CS_Category_Rev4			  = 0x05,
	AUDIO_OFFLOAD_SPDIF_CS_Category_Rev5			  = 0x06,
	AUDIO_OFFLOAD_SPDIF_CS_Category_Rev6			  = 0x07,
	AUDIO_OFFLOAD_SPDIF_CS_CopyRight_CP			   = 0x08,
	AUDIO_OFFLOAD_SPDIF_CS_CopyRight_NonCP			= 0x09,
	AUDIO_OFFLOAD_SPDIF_CS_SourceNumber_2			 = 0x0A,
	AUDIO_OFFLOAD_SPDIF_CS_SourceNumber_5			 = 0x0B,
	AUDIO_OFFLOAD_SPDIF_CS_SourceNumber_6			 = 0x0C,
	AUDIO_OFFLOAD_SPDIF_CS_SourceNumber_Rev1		  = 0x0D,
	AUDIO_OFFLOAD_SPDIF_CS_SourceNumber_Rev2		  = 0x0E,
	AUDIO_OFFLOAD_SPDIF_CS_SourceNumber_Rev3		  = 0x0F,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_A_Left	   = 0x10,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_B_Right	  = 0x11,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_C			= 0x12,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_D			= 0x13,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_E			= 0x14,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_F			= 0x15,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_G			= 0x16,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_H			= 0x17,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_I			= 0x18,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_J			= 0x19,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelNumber_K			= 0x1A,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_192				= 0x1B,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_176				= 0x1C,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_128				= 0x1D,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_96				 = 0x1E,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_88				 = 0x1F,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_64				 = 0x20,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_48				 = 0x21,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_44				 = 0x22,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_32				 = 0x23,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_24				 = 0x24,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_22				 = 0x25,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_16				 = 0x26,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_Rev1			   = 0x27,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_Rev2			   = 0x28,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_Rev3			   = 0x29,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_Rev4			   = 0x2A,
	AUDIO_OFFLOAD_SPDIF_CS_SmpFreq_Rev5			   = 0x2B,
	AUDIO_OFFLOAD_SPDIF_CS_ClockAcc_Lev1			  = 0x2C,
	AUDIO_OFFLOAD_SPDIF_CS_ClockAcc_Lev2			  = 0x2D,
	AUDIO_OFFLOAD_SPDIF_CS_ClockAcc_Lev3			  = 0x2E,
	AUDIO_OFFLOAD_SPDIF_CS_ClockAcc_NotMatch		  = 0x2F,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelAB_Invalid_ON		  = 0x30,
	AUDIO_OFFLOAD_SPDIF_CS_ChannelAB_Invalid_OFF		 = 0x31,
	AUDIO_OFFLOAD_SPDIF_CS_CopyProtect_CopyFree	   = 0x32,
	AUDIO_OFFLOAD_SPDIF_CS_CopyProtect_CopyOnce	   = 0x33,
	AUDIO_OFFLOAD_SPDIF_CS_CopyProtect_CopyNever	  = 0x34,
} AUDIO_OFFLOAD_SPDIF_CS_STATUS;

typedef enum {
	AUDIO_OFFLOAD_DIGITAL_SPDIF_OUTPUT,
	AUDIO_OFFLOAD_DIGITAL_HDMI_ARC_OUTPUT,
	AUDIO_OFFLOAD_DIGITAL_HDMI_OUTPUT,
	AUDIO_OFFLOAD_DIGITAL_I2S_OUTPUT,
	AUDIO_OFFLOAD_DIGITAL_MAX_OUTPUT,
} AUDIO_OFFLOAD_DIGITAL_OUTPUT_TYPE;

typedef enum {
	AUDIO_OFFLOAD_CODEC_NONE						  = 0x0,
	AUDIO_OFFLOAD_CODEC_LPCM						  = 0x1,
	AUDIO_OFFLOAD_CODEC_DD							= 0x2,
	AUDIO_OFFLOAD_CODEC_MPEG1						 = 0x3,
	AUDIO_OFFLOAD_CODEC_MP3						   = 0x4,
	AUDIO_OFFLOAD_CODEC_MPEG2						 = 0x5,
	AUDIO_OFFLOAD_CODEC_AAC						   = 0x6,
	AUDIO_OFFLOAD_CODEC_DTS						   = 0x7,
	AUDIO_OFFLOAD_CODEC_ATRAC						 = 0x8,
	AUDIO_OFFLOAD_CODEC_ONEBITAUDIO				   = 0x9,
	AUDIO_OFFLOAD_CODEC_DDP						   = 0xA,
	AUDIO_OFFLOAD_CODEC_DTSHD						 = 0xB,
	AUDIO_OFFLOAD_CODEC_TRUEHD						= 0xC,
	AUDIO_OFFLOAD_CODEC_DST						   = 0xD,
	AUDIO_OFFLOAD_CODEC_WMAPRO						= 0xE,
	AUDIO_OFFLOAD_CODEC_EXTENSION					 = 0xF,
	AUDIO_OFFLOAD_CODEC_MAX						   = 0x10,
} AUDIO_OFFLOAD_FORMAT_CODE;

typedef enum {
	AUDIO_OFFLOAD_HDMI_RX_PCM						 = 0x0,
	AUDIO_OFFLOAD_HDMI_RX_DD						  = 0x1,
	AUDIO_OFFLOAD_HDMI_RX_DTS						 = 0x2,
	AUDIO_OFFLOAD_HDMI_RX_DDP						 = 0x3,
	AUDIO_OFFLOAD_HDMI_RX_DP						  = 0x4,
	AUDIO_OFFLOAD_HDMI_RX_Other					   = 0x5,
	AUDIO_OFFLOAD_HDMI_RX_MAT						 = 0x6,
	AUDIO_OFFLOAD_HDMI_RX_DTS_HD					  = 0x7,
	AUDIO_OFFLOAD_HDMI_RX_MPEG_H					  = 0x8,
} AUDIO_OFFLOAD_HDMI_RX_TYPE;

typedef enum {
	AUDIO_OFFLOAD_SE_EQ,
	AUDIO_OFFLOAD_SE_PEQ,
	AUDIO_OFFLOAD_SE_Tone,
	AUDIO_OFFLOAD_SE_AutoVolume,
	AUDIO_OFFLOAD_SE_Surround,
	AUDIO_OFFLOAD_SE_Balance,
	AUDIO_OFFLOAD_SE_DRC,
	AUDIO_OFFLOAD_SE_KTVEcho,
	AUDIO_OFFLOAD_SE_Hpf,
	AUDIO_OFFLOAD_SE_FPC,
	AUDIO_OFFLOAD_SE_DcRemove,
	AUDIO_OFFLOAD_SE_EaseVol,
	AUDIO_OFFLOAD_SE_HeadPhoneSoundEffect,
	AUDIO_OFFLOAD_SE_DRC2,
	AUDIO_OFFLOAD_SE_SineTone,
	AUDIO_OFFLOAD_SE_VoiceEngineRef,
	AUDIO_OFFLOAD_SE_Limiter,
	AUDIO_OFFLOAD_SE_AllSoundEffect,

	AUDIO_OFFLOAD_SE_EQ_HP,
	AUDIO_OFFLOAD_SE_PEQ_HP,
	AUDIO_OFFLOAD_SE_Tone_HP,
	AUDIO_OFFLOAD_SE_AutoVolume_HP,
	AUDIO_OFFLOAD_SE_Surround_HP,
	AUDIO_OFFLOAD_SE_Balance_HP,
	AUDIO_OFFLOAD_SE_DRC_HP,
	AUDIO_OFFLOAD_SE_Hpf_HP,
	AUDIO_OFFLOAD_SE_SineTone_HP,
	AUDIO_OFFLOAD_SE_Limiter_HP,
} AUDIO_OFFLOAD_SE_Type;

typedef enum {
	AUDIO_OFFLOAD_SE_PARAM_PreScale,
	AUDIO_OFFLOAD_SE_PARAM_Balance,
	AUDIO_OFFLOAD_SE_PARAM_EQ,
	AUDIO_OFFLOAD_SE_PARAM_Surround_XA,
	AUDIO_OFFLOAD_SE_PARAM_Surround_XB,
	AUDIO_OFFLOAD_SE_PARAM_Surround_XK,
	AUDIO_OFFLOAD_SE_PARAM_Surround_LPFGAIN,
	AUDIO_OFFLOAD_SE_PARAM_Treble,
	AUDIO_OFFLOAD_SE_PARAM_Bass,
	AUDIO_OFFLOAD_SE_PARAM_AbsoluteBass,
	AUDIO_OFFLOAD_SE_PARAM_Avc_Mode,
	AUDIO_OFFLOAD_SE_PARAM_NR_Threshold,
	AUDIO_OFFLOAD_SE_PARAM_Avc_Threshold,
	AUDIO_OFFLOAD_SE_PARAM_Avc_AT,
	AUDIO_OFFLOAD_SE_PARAM_Avc_RT,
	AUDIO_OFFLOAD_SE_PARAM_AudioDelay,
	AUDIO_OFFLOAD_SE_PARAM_DCOffet,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_48K_A0,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_48K_A1,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_48K_A2,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_48K_B1,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_48K_B2,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_32K_A0,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_32K_A1,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_32K_A2,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_32K_B1,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_32K_B2,
	AUDIO_OFFLOAD_SE_PARAM_PEQ_SCALE,
	AUDIO_OFFLOAD_SE_PARAM_AbsoluteEQ,
	AUDIO_OFFLOAD_SE_PARAM_Drc_Threshold,
	AUDIO_OFFLOAD_SE_PARAM_DMAReader,
	AUDIO_OFFLOAD_SE_PARAM_AVC_S_Offset,
	AUDIO_OFFLOAD_SE_PARAM_Tone_Test_Fs,
	AUDIO_OFFLOAD_SE_PARAM_Tone_Test_Gain,
	AUDIO_OFFLOAD_SE_PARAM_AbsoluteBalance,
	AUDIO_OFFLOAD_SE_PARAM_AbsoluteTreble,
	AUDIO_OFFLOAD_SE_PARAM_Ease_Type_A,
	AUDIO_OFFLOAD_SE_PARAM_Ease_Duration_A,
	AUDIO_OFFLOAD_SE_PARAM_Ease_Gain_A,
	AUDIO_OFFLOAD_SE_PARAM_Ease_Target_Channel_A,
	AUDIO_OFFLOAD_SE_PARAM_Ease_Type_B,
	AUDIO_OFFLOAD_SE_PARAM_Ease_Duration_B,
	AUDIO_OFFLOAD_SE_PARAM_Ease_Gain_B,
	AUDIO_OFFLOAD_SE_PARAM_Ease_Target_Channel_B,
	AUDIO_OFFLOAD_SE_PARAM_Drc_Entry,
	AUDIO_OFFLOAD_SE_PARAM_Mixer_AD_Volume,
	AUDIO_OFFLOAD_SE_PARAM_Mixer_Main_Volume,
	AUDIO_OFFLOAD_SE_PARAM_VolFadingStep,
	AUDIO_OFFLOAD_SE_PARAM_VolFadingCtrl,
	AUDIO_OFFLOAD_SE_PARAM_BalanceMask,
	AUDIO_OFFLOAD_SE_PARAM_PhaseShiftMask,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch1,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch2,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch3,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch4,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch5,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch6,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch7,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch8,
	AUDIO_OFFLOAD_SE_PARAM_KTVEcho_XA,
	AUDIO_OFFLOAD_SE_PARAM_KTVEcho_XB,
	AUDIO_OFFLOAD_SE_PARAM_KTVEcho_ReverbStep,
	AUDIO_OFFLOAD_SE_PARAM_Avc_R_Begin,
	AUDIO_OFFLOAD_SE_PARAM_Avc_R_End,
	AUDIO_OFFLOAD_SE_PARAM_Avc_R_Slope,
	AUDIO_OFFLOAD_SE_PARAM_Sinetone_StartFreq,
	AUDIO_OFFLOAD_SE_PARAM_Sinetone_EndFreq,
	AUDIO_OFFLOAD_SE_PARAM_Sinetone_Duration,
	AUDIO_OFFLOAD_SE_PARAM_Sinetone_Mode,
	AUDIO_OFFLOAD_SE_PARAM_Sinetone_Ctrl,
	AUDIO_OFFLOAD_SE_PARAM_Sinetone_Gain,
	AUDIO_OFFLOAD_SE_PARAM_Pcm_Capture_Balence,
	AUDIO_OFFLOAD_SE_PARAM_Drc_AT,
	AUDIO_OFFLOAD_SE_PARAM_Drc_RT,
	AUDIO_OFFLOAD_SE_PARAM_Surround_Phase,
	AUDIO_OFFLOAD_SE_PARAM_VoiceEngineRef_PcmSource,
	AUDIO_OFFLOAD_SE_PARAM_VoiceEngineRef_PcmSampleRate,
	AUDIO_OFFLOAD_SE_PARAM_Limiter_Mode,
	AUDIO_OFFLOAD_SE_PARAM_Limiter_Threshold,
	AUDIO_OFFLOAD_SE_PARAM_ARCDelay,
	AUDIO_OFFLOAD_SE_PARAM_ChVol_By_Easing,
	AUDIO_OFFLOAD_SE_PARAM_Easing_Type,
	AUDIO_OFFLOAD_SE_PARAM_Easing_Duration,
	AUDIO_OFFLOAD_SE_PARAM_Easing_Gain,
	AUDIO_OFFLOAD_SE_PARAM_Easing_Ctrl,
	AUDIO_OFFLOAD_SE_PARAM_AIAQ,
	AUDIO_OFFLOAD_SE_PARAM_ChVol_Fading_Mode,
	AUDIO_OFFLOAD_SE_PARAM_EQ_Band_Num,
	AUDIO_OFFLOAD_SE_PARAM_EQ_Fc_Set,

	AUDIO_OFFLOAD_SE_PARAM_Balance_HP,
	AUDIO_OFFLOAD_SE_PARAM_AbsoluteBalance_HP,
	AUDIO_OFFLOAD_SE_PARAM_EQ_HP,
	AUDIO_OFFLOAD_SE_PARAM_Treble_HP,
	AUDIO_OFFLOAD_SE_PARAM_AbsoluteTreble_HP,
	AUDIO_OFFLOAD_SE_PARAM_Bass_HP,
	AUDIO_OFFLOAD_SE_PARAM_AbsoluteBass_HP,
	AUDIO_OFFLOAD_SE_PARAM_EQ_Band_Num_HP,
	AUDIO_OFFLOAD_SE_PARAM_EQ_Fc_Set_HP,
	AUDIO_OFFLOAD_SE_PARAM_EQ_Gain_Range,

	AUDIO_OFFLOAD_SE_PARAM_DRC_Band_Num,
	AUDIO_OFFLOAD_SE_PARAM_DRC_Band_Fc,
	AUDIO_OFFLOAD_SE_PARAM_DRC_Band_Num_HP,
	AUDIO_OFFLOAD_SE_PARAM_DRC_Band_Fc_HP,
	AUDIO_OFFLOAD_SE_PARAM_InternalDelay_Ch9,

	AUDIO_OFFLOAD_SE_PARAM_InputGain_Ch5,
	AUDIO_OFFLOAD_SE_PARAM_InputGain_Ch6,
	AUDIO_OFFLOAD_SE_PARAM_InputGain_Ch7,
	AUDIO_OFFLOAD_SE_PARAM_InputGain_Ch8,
	AUDIO_OFFLOAD_SE_PARAM_InputGain_Ch9,
	AUDIO_OFFLOAD_SE_PARAM_InputGain_Ch10,
	AUDIO_OFFLOAD_SE_PARAM_InputGain_Mch,
	AUDIO_OFFLOAD_SE_PARAM_InputGain_Enable,
	AUDIO_OFFLOAD_SE_PARAM_ChIIR_Enable,
	AUDIO_OFFLOAD_SE_PARAM_ChIIR_Fc,
} AUDIO_OFFLOAD_SE_PARAM;

typedef enum {
	AUDIO_OFFLOAD_SE_INFO_PreScale,
	AUDIO_OFFLOAD_SE_INFO_Balance_L,
	AUDIO_OFFLOAD_SE_INFO_Balance_R,
	AUDIO_OFFLOAD_SE_INFO_EQ,
	AUDIO_OFFLOAD_SE_INFO_Surround_XA,
	AUDIO_OFFLOAD_SE_INFO_Surround_XB,
	AUDIO_OFFLOAD_SE_INFO_Surround_XK,
	AUDIO_OFFLOAD_SE_INFO_Surround_LPFGAIN,
	AUDIO_OFFLOAD_SE_INFO_Treble,
	AUDIO_OFFLOAD_SE_INFO_Bass,
	AUDIO_OFFLOAD_SE_INFO_Avc_Mode,
	AUDIO_OFFLOAD_SE_INFO_Avc_Threshold,
	AUDIO_OFFLOAD_SE_INFO_Avc_AT,
	AUDIO_OFFLOAD_SE_INFO_Avc_RT,
	AUDIO_OFFLOAD_SE_INFO_AudioDelay,
	AUDIO_OFFLOAD_SE_INFO_DCOffet,
	AUDIO_OFFLOAD_SE_INFO_NR_Threshold,
	AUDIO_OFFLOAD_SE_INFO_NR_Status,
	AUDIO_OFFLOAD_SE_INFO_getSignal_Energy,
	AUDIO_OFFLOAD_SE_INFO_EQ_Status,
	AUDIO_OFFLOAD_SE_INFO_PEQ_Status,
	AUDIO_OFFLOAD_SE_INFO_Tone_Status,
	AUDIO_OFFLOAD_SE_INFO_AutoVolume_Status,
	AUDIO_OFFLOAD_SE_INFO_Surround_Status,
	AUDIO_OFFLOAD_SE_INFO_HPF_Status,
	AUDIO_OFFLOAD_SE_INFO_Drc_Threshold,
	AUDIO_OFFLOAD_SE_INFO_DMAReader_Buffer_Addr,
	AUDIO_OFFLOAD_SE_INFO_ToneTest_LEVEL,
	AUDIO_OFFLOAD_SE_INFO_FPC_Lpeak,
	AUDIO_OFFLOAD_SE_INFO_FPC_Rpeak,
	AUDIO_OFFLOAD_SE_INFO_Ease_Type_A,
	AUDIO_OFFLOAD_SE_INFO_Ease_Duration_A,
	AUDIO_OFFLOAD_SE_INFO_Ease_Gain_A,
	AUDIO_OFFLOAD_SE_INFO_Ease_Type_B,
	AUDIO_OFFLOAD_SE_INFO_Ease_Duration_B,
	AUDIO_OFFLOAD_SE_INFO_Ease_Gain_B,
	AUDIO_OFFLOAD_SE_INFO_InternalDelay_Ch1,
	AUDIO_OFFLOAD_SE_INFO_InternalDelay_Ch2,
	AUDIO_OFFLOAD_SE_INFO_InternalDelay_Ch3,
	AUDIO_OFFLOAD_SE_INFO_InternalDelay_Ch4,
	AUDIO_OFFLOAD_SE_INFO_InternalDelay_Ch5,
	AUDIO_OFFLOAD_SE_INFO_InternalDelay_Ch6,
	AUDIO_OFFLOAD_SE_INFO_InternalDelay_Ch7,
	AUDIO_OFFLOAD_SE_INFO_InternalDelay_Ch8,
	AUDIO_OFFLOAD_SE_INFO_KTVEcho_XA,
	AUDIO_OFFLOAD_SE_INFO_KTVEcho_XB,
	AUDIO_OFFLOAD_SE_INFO_KTVEcho_ReverbStep,
	AUDIO_OFFLOAD_SE_INFO_Avc_R_Begin,
	AUDIO_OFFLOAD_SE_INFO_Avc_R_End,
	AUDIO_OFFLOAD_SE_INFO_Avc_R_Slope,
	AUDIO_OFFLOAD_SE_INFO_Sinetone_StartFreq,
	AUDIO_OFFLOAD_SE_INFO_Sinetone_EndFreq,
	AUDIO_OFFLOAD_SE_INFO_Sinetone_Duration,
	AUDIO_OFFLOAD_SE_INFO_Sinetone_Mode,
	AUDIO_OFFLOAD_SE_INFO_Sinetone_Ctrl,
	AUDIO_OFFLOAD_SE_INFO_Ease_Gain_Max,
	AUDIO_OFFLOAD_SE_INFO_Ease_Gain_Min,
	AUDIO_OFFLOAD_SE_INFO_Sinetone_Gain,
	AUDIO_OFFLOAD_SE_INFO_Drc_AT,
	AUDIO_OFFLOAD_SE_INFO_Drc_RT,
	AUDIO_OFFLOAD_SE_INFO_Surround_Phase,
	AUDIO_OFFLOAD_SE_INFO_ARCDelay,
	AUDIO_OFFLOAD_SE_INFO_Easing_Type,
	AUDIO_OFFLOAD_SE_INFO_Easing_Duration,
	AUDIO_OFFLOAD_SE_INFO_Easing_Gain,
	AUDIO_OFFLOAD_SE_INFO_AIAQ,
	AUDIO_OFFLOAD_SE_INFO_AIAQ_Support,
	AUDIO_OFFLOAD_SE_INFO_Sinetone_Det_Fc,
	AUDIO_OFFLOAD_SE_INFO_Sinetone_Det_Level,
} AUDIO_OFFLOAD_SE_INFO;

typedef enum {
	AUDIO_OFFLOAD_ADC_COMPOSITE = 0,
	AUDIO_OFFLOAD_ADC_COMPONENT,
	AUDIO_OFFLOAD_ADC_VGA,
	AUDIO_OFFLOAD_ADC_DVI,
	AUDIO_OFFLOAD_ADC_MAX,
} AUDIO_OFFLOAD_ADC_SOURCE_TYPE;

typedef enum {
	AUDIO_OFFLOAD_OMX_SPDIF_OFF,
	AUDIO_OFFLOAD_OMX_SPDIF_ON,
	AUDIO_OFFLOAD_OMX_SPDIF_STOP,
	AUDIO_OFFLOAD_OMX_SPDIF_PLAY,
} AUDIO_OFFLOAD_OMX_SPDIF_Param;

typedef enum {
	AUDIO_OFFLOAD_AUDIO_FS_NONE,
	AUDIO_OFFLOAD_AUDIO_FS_8KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_11KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_12KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_16KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_22KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_24KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_32KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_44KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_48KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_64KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_88KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_96KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_176KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_192KHZ,
	AUDIO_OFFLOAD_AUDIO_FS_UNSUPPORT = 0xFF,
} AUDIO_OFFLOAD_AUDIO_FS_TYPE;

typedef enum {
	AUDIO_OFFLOAD_XPCM_TYPE_LPCM			 = 1,
	AUDIO_OFFLOAD_XPCM_TYPE_MS_ADPCM		 = 2,
	AUDIO_OFFLOAD_XPCM_TYPE_G711_A_LAW		 = 6,
	AUDIO_OFFLOAD_XPCM_TYPE_G711_u_LAW		 = 7,
	AUDIO_OFFLOAD_XPCM_TYPE_DVD_LPCM		 = 8,
	AUDIO_OFFLOAD_XPCM_TYPE_PRIVATE1_LPCM	 = 9,
	AUDIO_OFFLOAD_XPCM_TYPE_IMA_ADPCM		 = 17,
	AUDIO_OFFLOAD_XPCM_TYPE_IMA_ADPCM_APPLE	 = 18,
} AUDIO_OFFLOAD_XPCM_TYPE;

typedef enum {
	AVSYNC_OFFLOAD_STATE_WAIT_1ST_PTS,
	AVSYNC_OFFLOAD_STATE_WAIT_STC,
	AVSYNC_OFFLOAD_STATE_COMMON,
	AVSYNC_OFFLOAD_STATE_FREERUN,
} AVSYNC_OFFLOAD_STATE;

typedef enum {
	AUDIO_OFFLOAD_AU_SYS_NOT_READY,
	AUDIO_OFFLOAD_AU_SYS_M_BTSC,
	AUDIO_OFFLOAD_AU_SYS_M_EIAJ,
	AUDIO_OFFLOAD_AU_SYS_M_A2,

	AUDIO_OFFLOAD_AU_SYS_BG_A2,
	AUDIO_OFFLOAD_AU_SYS_DK1_A2,
	AUDIO_OFFLOAD_AU_SYS_DK2_A2,
	AUDIO_OFFLOAD_AU_SYS_DK3_A2,

	AUDIO_OFFLOAD_AU_SYS_BG_NICAM,
	AUDIO_OFFLOAD_AU_SYS_DK_NICAM,
	AUDIO_OFFLOAD_AU_SYS_I_NICAM,
	AUDIO_OFFLOAD_AU_SYS_L_NICAM,
	AUDIO_OFFLOAD_AU_SYS_FM_RADIO,
	AUDIO_OFFLOAD_AU_SYS_HI_DEV = 0x10,
	AUDIO_OFFLOAD_AU_SYS_BUSY = 0x80,
	AUDIO_OFFLOAD_STD_SEL_AUTO = 0xE0
} AUDIO_OFFLOAD_AUDIO_SIF_SET_STANDARD;

typedef enum {
	AUDIO_OFFLOAD_CARRIER1_ON_AMP = 0x00,
	AUDIO_OFFLOAD_CARRIER1_OFF_AMP,
	AUDIO_OFFLOAD_CARRIER1_ON_NSR,
	AUDIO_OFFLOAD_CARRIER1_OFF_NSR,
	AUDIO_OFFLOAD_CARRIER2_ON_AMP,
	AUDIO_OFFLOAD_CARRIER2_OFF_AMP,
	AUDIO_OFFLOAD_CARRIER2_ON_NSR,
	AUDIO_OFFLOAD_CARRIER2_OFF_NSR,
	AUDIO_OFFLOAD_A2_PILOT_ON_AMP,
	AUDIO_OFFLOAD_A2_PILOT_OFF_AMP,

	AUDIO_OFFLOAD_NICAM_ON_SIGERR = 0x0,
	AUDIO_OFFLOAD_NICAM_OFF_SIGERR = 0x1,

	AUDIO_OFFLOAD_BTSC_MONO_ON_NSR_RATIO = 0x0,
	AUDIO_OFFLOAD_BTSC_MONO_OFF_NSR_RATIO = 0x1,
	AUDIO_OFFLOAD_BTSC_PILOT_AMPLITUDE_ON = 0x2,
	AUDIO_OFFLOAD_BTSC_PILOT_AMPLITUDE_OFF = 0x3,
	AUDIO_OFFLOAD_BTSC_SAP_ON_NSR_RATIO = 0x4,
	AUDIO_OFFLOAD_BTSC_SAP_OFF_NSR_RATIO = 0x5,
	AUDIO_OFFLOAD_BTSC_STEREO_ON_RATIO = 0x6,
	AUDIO_OFFLOAD_BTSC_STEREO_OFF_NSR_RATIO = 0x7,
	AUDIO_OFFLOAD_BTSC_SAP_AMPLITUDE_ON = 0x8,
	AUDIO_OFFLOAD_BTSC_SAP_AMPLITUDE_OFF = 0x9,
	AUDIO_OFFLOAD_BTSC_HIDEV_ON_NSR_RATIO = 0xA,
	AUDIO_OFFLOAD_BTSC_HIDEV_OFF_NSR_RATIO = 0xB
} AUDIO_OFFLOAD_AUDIO_SIF_THRESHOLD_TYPE;
/*----------------------------------------------------*/
/* struct*/
/*----------------------------------------------------*/
typedef struct __attribute__((packed)) {
	unsigned char bStart;
	unsigned char bConnect;
	unsigned char bAVSyncOn;
	unsigned char bIsAD;
	AUDIO_OFFLOAD_OUTPORT_SOURCE_TYPE eGroup;
	AUDIO_OFFLOAD_DSP_ID eDSPId;
	AUDIO_OFFLOAD_SOURCE_INFO_TYPE eSourceType;
	AUDIO_OFFLOAD_DEC_FORMAT eAudFormat;
	AUDIO_OFFLOAD_STC_SOURCE eStcSource;
	AUDIO_OFFLOAD_AFIFO_SOURCE eAfifoSource;
	AUDIO_OFFLOAD_MM_TYPE eMMType;
	AUDIO_OFFLOAD_FORCE_ADEC_ID eAudio_Force_ID;
	int s32PTSOffset;
} AUDIO_OFFLOAD_AUDIODECSTATUS_ST;

typedef struct {
	unsigned char	support_codec;
	unsigned char	support_ch;
	unsigned char	support_samplerate;
	unsigned char	support_SAD_byte3;
} AUDIO_OFFLOAD_DEVICE_CAPABILITY_ST;

typedef struct {
	unsigned int aes_base_addr;
	unsigned int aes_end_addr;
	unsigned int aes_BufSize;
	unsigned int aes_write_addr;
	unsigned int aes_read_addr;
	unsigned int aes_freeSpace;
	unsigned int aes_level;
	unsigned int aes_ptsCnt;
	unsigned long long aes_lastPTS;
	unsigned int aes_specificBufSize;
} AUDIO_OFFLOAD_AES_INFO;

typedef struct {
	AUDIO_OFFLOAD_OUTPUT_TYPE	SpeakerOut;
	AUDIO_OFFLOAD_OUTPUT_TYPE	HpOut;
	AUDIO_OFFLOAD_OUTPUT_TYPE	MonitorOut;
	AUDIO_OFFLOAD_OUTPUT_TYPE	ScartOut;
	AUDIO_OFFLOAD_OUTPUT_TYPE	SpdifOut;
	AUDIO_OFFLOAD_OUTPUT_TYPE	ArcOut;
	AUDIO_OFFLOAD_OUTPUT_TYPE	HDMIOut;
} AUDIO_OFFLOAD_OUT_INFO;

typedef struct {
	AUDIO_OFFLOAD_PATH_TYPE	  SpeakerOut;
	AUDIO_OFFLOAD_PATH_TYPE	  HpOut;
	AUDIO_OFFLOAD_PATH_TYPE	  MonitorOut;
	AUDIO_OFFLOAD_PATH_TYPE	  ScartOut;
	AUDIO_OFFLOAD_PATH_TYPE	  SpdifOut;
	AUDIO_OFFLOAD_PATH_TYPE	  ArcOut;
	AUDIO_OFFLOAD_PATH_TYPE	  HDMIOut;
} AUDIO_OFFLOAD_PATH_INFO;

typedef struct audio_offload_parm {
	unsigned char AUD_OFFLOAD_ID;
	unsigned char AUD_OFFLOAD_PARM[247];
	unsigned char AUD_OFFLOAD_RETURN[8];
} AUDIO_OFFLOAD_PARM;

typedef struct audio_duplex_parm {
	unsigned char AUD_DUPLEX_ID;
	unsigned char AUD_DUPLEX_PARM[247];
	unsigned char AUD_DUPLEX_RETURN[8];
} AUDIO_DUPLEX_PARM;

typedef struct audio_capture_parm {
	unsigned char AUD_CAPTURE_ID;
	unsigned char AUD_CAPTURE_PARM[247];
	unsigned char AUD_CAPTURE_RETURN[8];
} AUDIO_CAPTURE_PARM;

typedef struct audio_SetDspBaseAddr_struct {
	unsigned char u8Index;
	unsigned int u32Bin_Base_Address;
	unsigned int u32Mad_Base_Buffer_Adr;
} AUDIO_OFFLOAD_SET_BASE_ADDR_ST;

typedef struct audio_InputSwitch_struct {
	AUDIO_OFFLOAD_INPUT_TYPE enSource;
	AUDIO_OFFLOAD_SWITCH_GROUP enGroup;
} AUDIO_OFFLOAD_INPUT_SWITCH_ST;

typedef struct audio_SetMixModeMute_struct {
	AUDIO_OFFLOAD_SOURCE_INFO_TYPE eSourceType;
	AUDIO_OFFLOAD_MIX_VOL_TYPE VolType;
	unsigned char EnMute;
} AUDIO_OFFLOAD_SET_MIX_MODE_MUTE_ST;

typedef struct audio_SetMixModeVolume_struct {
	AUDIO_OFFLOAD_SOURCE_INFO_TYPE eSourceType;
	AUDIO_OFFLOAD_MIX_VOL_TYPE VolType;
	unsigned char u8Vol1;
	unsigned char u8Vol2;
} AUDIO_OFFLOAD_SET_MIX_MODE_VOL_ST;

typedef struct audio_SetAbsoluteVolume_struct {
	unsigned char u8Path;
	unsigned char u8Vol1;
	unsigned char u8Vol2;
} AUDIO_OFFLOAD_SET_ABS_VOL_ST;

typedef struct audio_SetMute_struct {
	unsigned char u8Path;
	unsigned char EnMute;
} AUDIO_OFFLOAD_SET_MUTE_ST;

typedef struct audio_GetDecodeSystem_struct {
	AUDIO_OFFLOAD_DEC_ID DecId;
	unsigned long long p_AudioDecStatus;
	/* store a pointer to AUDIO_OFFLOAD_AUDIODECSTATUS_ST*/
} AUDIO_OFFLOAD_GET_DEC_SYSTEM_ST;

typedef struct audio_SetDecodeSystem_struct {
	AUDIO_OFFLOAD_DEC_ID DecId;
	AUDIO_OFFLOAD_AUDIODECSTATUS_ST AudioDecStatus;
} AUDIO_OFFLOAD_SET_DEC_SYSTEM_ST;

typedef struct audio_SetMpegInfo_struct {
	AUDIO_OFFLOAD_MPEG_INFOTYPE infoType;
	unsigned int param1;
	unsigned int param2;
} AUDIO_OFFLOAD_SET_MPEG_PARAM_ST;

typedef struct audio_SetAC3PInfo_struct {
	AUDIO_OFFLOAD_AC3P_INFOTYPE infoType;
	unsigned int param1;
	unsigned int param2;
} AUDIO_OFFLOAD_SET_AC3P_PARAM_ST;

typedef struct audio_SetASFParm_struct {
	AUDIO_OFFLOAD_WMA_ASF_PARMTYPE parm_type;
	unsigned int value;
} AUDIO_OFFLOAD_SET_ASF_PARAM_ST;

typedef struct audio_SetDecodeCmd_struct {
	AUDIO_OFFLOAD_DEC_ID DecId;
	AUDIO_OFFLOAD_DVB_DECCMDTYPE enDecComamnd;
} AUDIO_OFFLOAD_SET_DEC_CMD_ST;

typedef struct __attribute__((packed)) {
	AUDIO_OFFLOAD_Comm_infoType infoType;
	unsigned long long param1;
	unsigned long long param2;
} AUDIO_OFFLOAD_SET_COMM_INFO_ST;

typedef struct __attribute__((packed)) {
	AUDIO_OFFLOAD_DEC_ID DecId;
	AUDIO_OFFLOAD_ParamType paramType;
	unsigned long long Param;
	unsigned int size;
} AUDIO_OFFLOAD_SET_AUD_PARAM2_ST;

typedef struct __attribute__((packed)) {
	AUDIO_OFFLOAD_DEC_ID DecId;
	AUDIO_OFFLOAD_InfoType infoType;
	unsigned long long u64Info;
	/* store a pointer to void* */
	unsigned int size;
} AUDIO_OFFLOAD_GET_AUD_INFO2_ST;

typedef struct audio_GetCommAudioInfo_struct {
	AUDIO_OFFLOAD_Comm_infoType infoType;
} AUDIO_OFFLOAD_GET_COMM_INFO_ST;

typedef struct __attribute__((packed)) {
	unsigned int u32StrCmdLength;
	unsigned char *pStrCmd;
} AUDIO_OFFLOAD_SYS_CTRL_ST;

typedef struct audio_SIF_SendCmd_struct {
	AUDIO_OFFLOAD_SIF_CmdType enAudSifCommand;
	unsigned char comm_arg1;
	unsigned char comm_arg2;
} AUDIO_OFFLOAD_SIF_SEND_CMD_ST;

typedef struct audio_SIF_SetPrescale_struct {
	unsigned char configU8;
	int configS32;
} AUDIO_OFFLOAD_SIF_SET_PRESCALE_ST;

typedef struct {
	unsigned char HiByteValue;
	unsigned char LowByteValue;
} AUDIO_OFFLOAD_THR_TBL_TYPE_ST;

typedef struct audio_SPDIF_SetSCMS_struct {
	unsigned char C_bit_en;
	unsigned char L_bit_en;
} AUDIO_OFFLOAD_SPDIF_SET_SCMS_ST;

typedef struct audio_SPDIF_ChannelStatus_CTRL_struct {
	AUDIO_OFFLOAD_SPDIF_CS_TYPE cs_mode;
	AUDIO_OFFLOAD_SPDIF_CS_STATUS status;
} AUDIO_OFFLOAD_SPDIF_CS_CTRL_ST;

typedef struct audio_DigitalOut_SetDeviceCapability_struct {
	AUDIO_OFFLOAD_DIGITAL_OUTPUT_TYPE eoutType;
	AUDIO_OFFLOAD_FORMAT_CODE ecodecType;
	AUDIO_OFFLOAD_DEVICE_CAPABILITY_ST codecCapability;
} AUDIO_OFFLOAD_SET_DEVICE_CAPABILITY_ST;

typedef struct AUDIO_OFFLOAD_PCM_OPEN_struct {
	unsigned int u32StructVersion;
	/* version number of this data structure */
	unsigned int u32StructSize;
	/* size of this data structure */
	unsigned char u8ConnectFlag;
	/* it is TRUE when opened */
	unsigned char u8StartFlag;
	/* it is TRUE when started and opened */
	unsigned char u8Name[AUDIO_COMMON_PCM_IO_NAME_LENGTH];
	/* if set the skip name, it will skip the same name of DMA when open */
	unsigned char u8SkipName[AUDIO_COMMON_PCM_IO_NAME_LENGTH];
	/* The PCM name requested */
	unsigned char u8NonBlockingFlag;
	/* it is TRUE when request for nonblocking mode */
	unsigned char u8MultiChFlag;
	/* it is TRUE when request for a multi-channel PCM IO */
	unsigned char u8MixingFlag;
	/* it is TRUE when request for a mixing PCM IO */
	unsigned int u32MixingGroup;
	/* PCM mixing group, i.e. AUDIO_PCMMIXER_GROUP_ALL */

	unsigned int u32BufferDuration;
	unsigned int u32Channel;
	/* PCM channel number */
	unsigned int u32SampleRate;
	/* PCM sample rate */
	unsigned int u32BitWidth;
	/* PCM sample's bit width of each channel */
	unsigned int u32BigEndian;
	/* PCM endian, TRUE means Big Endian, FALSE means Little Endian */
	unsigned int u32Timestamp;
	/* PCM timestamp */
	unsigned int u32Weighting;
	unsigned int u32Volume;
	/* PCM volume, the range is 0 ~ 1016, and 96 means 0dB */
	unsigned int u32BufferLevel;
	/* PCM bufffer level in byte unit */
	unsigned char u8CaptureFlag;
	/* it is TRUE when request for a PCM Capture IO */
	unsigned char u8PcmSoundFlag;
	unsigned char u8DelayFlag;
	unsigned char u8FloatFlag;
	/* it is TRUE when request for float PCM */
} __attribute__((packed)) AUDIO_OFFLOAD_PCM_OPEN_ST;

typedef struct audio_PCM_Set_struct {
	int s32DeviceId;
	unsigned int u32Cmd;
	AUDIO_OFFLOAD_VIRT virtData;
	unsigned int size;
} AUDIO_OFFLOAD_PCM_SET_ST;

typedef struct audio_PCM_Get_struct {
	int s32DeviceId;
	unsigned int u32Cmd;
	AUDIO_OFFLOAD_VIRT virtData;
	unsigned int size;
} AUDIO_OFFLOAD_PCM_GET_ST;

typedef struct audio_PCM_Read_struct {
	int s32DeviceId;
	AUDIO_OFFLOAD_VIRT virtBuf;
	unsigned int u32Size;
} AUDIO_OFFLOAD_PCM_READ_ST;

typedef struct audio_PCM_Write_struct {
	int s32DeviceId;
	unsigned int u32Size;
	unsigned long long u64Buf;
} AUDIO_OFFLOAD_PCM_WRITE_ST;

typedef struct {
	unsigned int u32DecodeFrame;
	unsigned int u32WrtAddr;
	unsigned int u32WrtBytes;
	/* TVOS2.0 DTV */
	signed long long s64CPTS;
	unsigned int u32FrameSize;
	unsigned int u32ReadAddr;
	unsigned int u32Channels;
	unsigned int u32Bps;
	unsigned int u32SampleRate;
	unsigned int u32WriteAddr;
} AUDIO_OFFLOAD_PCM_MM_Info_ST;

typedef struct audio_ES_Write_struct {
	int s8DecoderId;
	unsigned int u32Size;
	unsigned long long u64Buf;
	unsigned int aes_write_addr;
} AUDIO_OFFLOAD_ES_WRITE_ST;

typedef struct audio_Decoded_PCM_Read_struct {
	int s8DecoderId;
	unsigned int u32Size;
	unsigned long long u64Buf;
	unsigned int u32CurrentPhyAddr;
} AUDIO_OFFLOAD_DECODED_PCM_READ_ST;

typedef struct audio_SND_ProcessEnable_struct {
	AUDIO_OFFLOAD_SE_Type Type;
	unsigned char enable;
} AUDIO_OFFLOAD_SND_PROC_EN_ST;

typedef struct audio_SND_SetParam1_struct {
	AUDIO_OFFLOAD_SE_PARAM Type;
	unsigned short param1;
	unsigned short param2;
} AUDIO_OFFLOAD_SND_SET_PARAM_ST;

typedef struct audio_SND_GetParam1_struct {
	AUDIO_OFFLOAD_SE_INFO Type;
	unsigned short param1;
} AUDIO_OFFLOAD_SND_GET_PARAM_ST;

typedef struct audio_SOUND_GetParam_struct {
	const signed char *pStrCmd;
	unsigned int u32StrCmdLength;
	signed char *pData;
	unsigned int u32DataSize;
} AUDIO_OFFLOAD_SOUND_GET_PARAM_ST;

typedef struct audio_SoundEffect_SetParam_struct {
	unsigned long long u64StrCmd;
	unsigned int u32StrCmdLength;
	unsigned long long u64Data;
	unsigned int u32DataSize;
} AUDIO_OFFLOAD_SE_SET_PARAM_ST;

typedef struct audio_ADVSOUND_SubProcessEnable_struct {
	unsigned long long u64proc;
	unsigned int u32procStrLen;
	unsigned char enable;
} AUDIO_OFFLOAD_ADVSE_SUBPROC_EN_ST;

typedef struct audio_ADVSND_SetParam_struct {
	unsigned long long u64param;
	unsigned int u32paramStrLen;
	unsigned int u32value1;
	unsigned short u16value2;
} AUDIO_OFFLOAD_ADVSE_SET_PARAM_ST;

typedef struct audio_COPY_Parameter_struct {
	unsigned long long u64type;
	unsigned int u32typeStrLen;
	unsigned long long u64Parameter;
	unsigned int size;
} AUDIO_OFFLOAD_COPY_PARAM_ST;

typedef struct audio_MM2_checkAesInfo_struct {
	AUDIO_OFFLOAD_DEC_ID  dec_id;
	unsigned long long aes_info;
	/* store a pointer to AUDIO_OFFLOAD_AES_INFO*/
} AUDIO_OFFLOAD_MM_CHECK_AES_INFO_ST;

typedef struct audio_MM2_inputAesFinished_struct {
	AUDIO_OFFLOAD_DEC_ID dec_id;
	unsigned int es_size;
	unsigned char ptsExist;
	unsigned long long pts;
} AUDIO_OFFLOAD_MM_INPUT_AES_FINISH_ST;

typedef struct {
	unsigned short Channels[AUDIO_OFFLOAD_COOK_MAX_NUM_CODECS];
	unsigned short Regions[AUDIO_OFFLOAD_COOK_MAX_NUM_CODECS];
	unsigned short cplStart[AUDIO_OFFLOAD_COOK_MAX_NUM_CODECS];
	unsigned short cplQbits[AUDIO_OFFLOAD_COOK_MAX_NUM_CODECS];
	unsigned short FrameSize[AUDIO_OFFLOAD_COOK_MAX_NUM_CODECS];

	unsigned short mNumCodecs;
	unsigned short mSamples;
	unsigned short mSampleRate;
} AUDIO_OFFLOAD_COOK_ST;

typedef struct {
	AUDIO_OFFLOAD_XPCM_TYPE audioType;
	unsigned int sampleRate;
	unsigned short blockSize;
	unsigned short samplePerBlock;
	unsigned char channels;
	unsigned char bitsPerSample;
} AUDIO_OFFLOAD_XPCM_ST;

typedef struct {
	AUDIO_OFFLOAD_DEC_ID DecId;
	unsigned char enable;
} AUDIO_OFFLOAD_SYNC_MODE_ST;

typedef struct Cpu_Audio_RegByteParam_struct {
	unsigned int addr;
	unsigned int mask;
	unsigned int val;
} CPU_AUDIO_REG_BYTE_PARAM_ST;

typedef struct Cpu_Audio_SetInterruptToCoprocessor_struct {
	unsigned int u32Cmd;     ///< [IN]: Interrupt cmd
	unsigned int u32CmdParam;     ///< [IN]: Interrupt cmd
} CPU_AUDIO_SET_INTERRUPT_TO_COPROCESSOR_ST;

typedef struct {
	unsigned char u8StrCmd[64];
	unsigned long long u64Data;
} AUDIO_OFFLOAD_COMMON_CMD_t;

typedef struct __attribute__((packed)) {
	unsigned char miu;
	unsigned char tv_system;
	unsigned char dtv_system;
	unsigned char au_system_sel;

	AUDIO_OFFLOAD_AUDIO_SIF_SET_STANDARD standard_u8Type;
	AUDIO_OFFLOAD_AUDIO_SIF_THRESHOLD_TYPE threshold_u8Type;
	unsigned short threshold_value;
} AUDIO_OFFLOAD_AUDIO_INIT_INFO_ST;

typedef struct audio_atv_threshold_struct {
	unsigned long long u64Parameter;
	unsigned int size;
} AUDIO_OFFLOAD_ATV_THRESHOLD_ST;

struct AUDIO_OFFLOAD_TLVROWDATA_S {
	unsigned int u32MpuSequenceNumber;            /// MPU sequence number
	unsigned int u32AuIndexInMpu;                 /// Count of AU, max number is num_of_au
	unsigned long long u64TlvPts;                       /// Pts from dmx, units is 2^24hz
};

struct AUDIO_OFFLOAD_PUSHTLVPARAMS_S {
	AUDIO_OFFLOAD_DEC_ID dec_id;
	struct AUDIO_OFFLOAD_TLVROWDATA_S *psTlvRowData;   /// Pointer to TLV row data
	unsigned short u16Size;                         /// row number of pushed data
};

struct audio_offload_hwdep_reg {
	unsigned int address;
	unsigned short u16mask;
	unsigned short u16val;
};

struct audio_offload_hwdep_string_cmd {
	unsigned long long str_cmd;
	unsigned int str_len;
};
#endif /* __LINUX_SND_OFFLOAD_MEDIATEK_H */
