/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef _DT_BINDINGS_CLK_MT5896_NONPM_ADCEN_H
#define _DT_BINDINGS_CLK_MT5896_NONPM_ADCEN_H

#define CLK_NONPM_ADC_EN_ADC2ADC	1
#define CLK_NONPM_ADC_EN_ADC2MIU2ADC	2
#define CLK_NONPM_ADC_EN_ADC2MIUSC2ADC	3
#define CLK_NONPM_ADC_EN_ADC2SC2ADC	4
#define CLK_NONPM_ADC_EN_ADCPLL2002ADC	5
#define CLK_NONPM_ADC_EN_ADCPLL4002ADC	6
#define CLK_NONPM_ADC_EN_B_ADC2ADC	7
#define CLK_NONPM_ADC_EN_B_INT2ADC	8
#define CLK_NONPM_ADC_EN_CLKPLL2ADC	9
#define CLK_NONPM_ADC_EN_CVBS_DAC_A_DIGITAL0_MUX2ADC	10
#define CLK_NONPM_ADC_EN_CVBS_DAC_A_DIGITAL02ADC	11
#define CLK_NONPM_ADC_EN_CVBS_DAC_A_DIGITAL12ADC	12
#define CLK_NONPM_ADC_EN_DIG_2162ADC	13
#define CLK_NONPM_ADC_EN_FBLANK2ADC	14
#define CLK_NONPM_ADC_EN_FSC_VD2ADC	15
#define CLK_NONPM_ADC_EN_G_ADC2ADC	16
#define CLK_NONPM_ADC_EN_G_INT2ADC	17
#define CLK_NONPM_ADC_EN_ISOG2ADC	18
#define CLK_NONPM_ADC_EN_NCO_CLK2ADC	19
#define CLK_NONPM_ADC_EN_R_ADC2ADC	20
#define CLK_NONPM_ADC_EN_R_INT2ADC	21
#define CLK_NONPM_ADC_EN_VD_ICLAMP2ADC	22
#define CLK_NONPM_ADC_EN_VD_ICLAMP2VIDEO_ATOP	23
#define CLK_NONPM_ADC_EN_VD_NCO_CLK2ADC	24
#define CLK_NONPM_ADC_EN_VD2ADC	25
#define CLK_NONPM_ADC_EN_VDPLL4002ADC	26
#define CLK_NONPM_ADC_EN_XTAL12_4INTERRUPT2ADC	27
#define CLK_NONPM_ADC_EN_XTAL12_4PLUGDET2ADC	28
#define CLK_NONPM_ADC_EN_XTAL122ADC	29
#define CLK_NONPM_ADC_EN_XTAL242ADC	30
#define CLK_NONPM_ADC_EN_Y_ADC2ADC	31
#define CLK_NONPM_ADC_EN_Y_INT2ADC	32
#define CLK_NONPM_ADC_EN_YUV_ADC2ADC	33
#define CLK_NONPM_ADC_EN_REG_ADCPLL_TEST_ENABLE	34
#define CLK_NONPM_ADC_EN_REG_ADCPLL_TEST_DIV_SEL	35
#define CLK_NONPM_ADC_EN_REG_ADCPLL_TEST_SRC_SEL	36
#define CLK_NONPM_ADC_EN_VD2MHEG5_ADC	37
#define CLK_NONPM_ADC_EN_VD2X2MHEG5_ADC	38
#define CLK_NONPM_ADC_EN_ADCPLB_MPLL2ADC	39
#define CLK_NONPM_ADC_EN_CLKD_ADC2ADC_TOP_DATA	40
#define CLK_NONPM_ADC_EN_CLKD_ADC2GEMIU2ADC_TOP_DATA	41
#define CLK_NONPM_ADC_EN_CLKD_ADC2SC2ADC_TOP_DATA	42
#define CLK_NONPM_ADC_EN_CLKD_VD2ADC_TOP_DATA	43
#define CLK_NONPM_ADC_EN_CLKFSCX2_VD2ADC_TOP_DATA	44
#define CLK_NONPM_ADC_EN_NR	45

#endif
