/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef _DT_BINDINGS_CLK_MT5896_SMART_H
#define _DT_BINDINGS_CLK_MT5896_SMART_H

#define CLK_SMART_EN_SMART2PIU	1
#define CLK_SMART_EN_SMART_SYNTH_272PIU 2
#define CLK_SMART_EN_SMART_SYNTH_4322PIU	3
#define CLK_SMART_EN_MCU_NONPM2SMART0	4
#define CLK_SMART_EN_NR	5

#define CLK_SMART2_EN_SMART22PIU	1
#define CLK_SMART2_EN_SMART2_SYNTH_272PIU	2
#define CLK_SMART2_EN_SMART2_SYNTH_4322PIU	3
#define CLK_SMART2_EN_MCU_NONPM2SMART1	4
#define CLK_SMART2_EN_NR	5
#endif

