/* SPDX-License-Identifier: (GPL-2.0 OR BSD-3-Clause) */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#define CLK_USB_PM_EN_MCU_PM2PM_SSUSB	1
#define CLK_USB_PM_EN_SMI2PM_SSUSB	2
#define CLK_USB_PM_EN_SSUSB_SYS2PM_SSUSB	3
#define CLK_USB_PM_EN_SSUSB_XHCI2PM_SSUSB	4
#define CLK_USB_PM_EN_SSUSB_FRMCNT2PM_SSUSB	5
#define CLK_USB_PM_EN_XTAL_24M_PM2PM_SSUSB	6
#define CLK_USB_PM_EN_SSUSB_PCLK2PM_SSUSB	7
#define CLK_USB_PM_EN_SSUSB_UTMI2PM_SSUSB	8
#define CLK_USB_PM_EN_SSUSB_SCL2PM_SSUSB	9
#define CLK_USB_PM_EN_SSUSB_SDIN2PM_SSUSB	10
#define CLK_USB_PM_EN_MCU_PM2SSUSB_U2PHY	11
#define CLK_USB_PM_EN_XTAL_24M_PM2PM_SSUSB_U3PHY	12
#define CLK_USB_PM_EN_XTAL_24M_PM2SSUSB_U2PHY	13
#define CLK_USB_PM_EN_MCU_PM2PM_PEXTP	14
#define CLK_USB_PM_EN_PEXTP_TL2PM_PEXTP	15
#define CLK_USB_PM_EN_SMI2PM_PEXTP	16
#define CLK_USB_PM_EN_XTAL_24M_PM2PM_PEXTP	17
#define CLK_USB_PM_EN_NR	18
